### ISSUE TITLE
BeforeShow isn't fired just before show

### ISSUE THREAD

**Issue by alexbudarov** [Haulmont/jmix-ui#118]
The problem is discussed here: https://github.com/cuba-platform/cuba/issues/2947
BeforeShow event really isn't fired "before show". There are some screen lifecycle actions that occur after BeforeShow handler.

Possible solutions:
- Introduce new event
- Fix BeforeShow. Make it fire after all screen operations are finished, just before the screen is shown.

**Comment by glebfox** [comment]
We can't load data during a screen creation, e.g. in `AfterInitEvent`, because data loading may require additional parameters that can be set after a screen is created. Introducing the new event is redundant, the docs will be updated instead.
