### ISSUE TITLE
Implement exception handler for UniqueConstraintViolation situations

### ISSUE THREAD

**Issue by alexbudarov** [Haulmont/jmix-ui#119]
As I see, io.jmix.ui.exception.ExceptionHandler exists but it doesn't have descendants for specific situations.

E.g. in jmix project template User#username is unique.

Currently "username is duplicate" error is handled like this:
![image](https://user-images.githubusercontent.com/6158807/95341397-44c1d580-08c7-11eb-88c7-980ebd401916.png)

**Comment by gorbunkov** [comment]
See https://doc.cuba-platform.com/manual-7.2/unique_constraint_violation_exceptions.html

Message key should have a `databaseUniqueConstraintViolation` prefix, e.g.
```
databaseUniqueConstraintViolation.IDX_SEC_USER_UNIQ_LOGIN = A user with the same login already exists
```
