### ISSUE TITLE
Support in_list and not_in_list operations in PropertyFilter component

### ISSUE THREAD

**Issue by gorbunkov** [Haulmont/jmix-ui#142]
When **in_list** or **not_in_list** operation is set for the PropertyFilter component, then the component should render a proper layout for editing list value.

The following requirements should be met:
* The component should be able to select list of entities
* The component should be able to define a list of primitive types (strings, numbers, dates)

See haulmont/jmix-ui#29

### QA
Check the `IN_LIST` and `NOT_IN_LIST` operations of the `PropertyFilter` component for the component itself and within `Filter` component.
Check for different data types.

**Comment by maistrenkoIulia** [comment]
The component should allow to enter a comma-separated list of strings and numbers - doesn`t work
![image](https://user-images.githubusercontent.com/66992566/108493808-3695b400-72c0-11eb-9732-a9669c7b5b71.png)

2. Remove duplicates in case value has already input to list
![image](https://user-images.githubusercontent.com/66992566/108493935-5fb64480-72c0-11eb-853a-0ec759e5ea15.png)

3. TC: create 3 entities with value of enum = EMPTY/ Offline / empty field
set filter not in list > add value = EMPTY
ER: entites with Offline / empty field should be displayed
AR: only entity with Offline value displayes
[list.zip](https://github.com/Haulmont/jmix-ui/files/6009341/list.zip)

**Comment by GlebDurygin** [comment]
1) The `ValuesPicker` component does not have this functionality
2) Will be fixed in Haulmont/jmix-ui#332
3) Actual behavior is correct
