### ISSUE TITLE
Join is_set and is_not_set operations for PropertyFilter component

### ISSUE THREAD

**Issue by gorbunkov** [Haulmont/jmix-ui#145]
Right now the PropertyFilter (see #29) supports separate is_set and is_not_set operations. For these operations a combo box with a single value "True" is displayed.

The task is to have only one operation: **is_set**. The ComboBox component for this operation displays two values: true and false. If true is selected then the "is not null" operation will be added to JPQL statement. If "false" is selected then "is null" should be used in JPQL

### QA
Check the IS_SET operation of the PropertyFilter component for the component itself and within Filter component.

**Comment by maistrenkoIulia** [comment]
TC:
create runtime filter> create group condition> add for int attr is_set operator>ok

ER: dropdown list should display for int attr
AR: text field appeares
![image](https://user-images.githubusercontent.com/66992566/107742030-bdc6b300-6d27-11eb-920b-e789ee76ed85.png)

**Comment by GlebDurygin** [comment]
Will be fixed in #346
