### ISSUE TITLE
New generic filter standalone component

### ISSUE THREAD

**Issue by knstvk** [Haulmont/jmix-ui#162]
#### Filter actions
- [x] Implement `FilterSaveAction`, `FilterSaveAsAction` classes;
- [x] Implement `FilterEditAction` class;
- [x] Implement `FilterRemoveAction` class;
- [x] Implement `FilterClearValuesAction` class;
- [x] Implement `FilterCopyAction` class;
- [x] Implement `FilterAddConditionAction` class;

#### Behavior 
- [x] Implement `AddConditionScreen`;
- [x] Add single condition based on `PropertyFilter` component;
- [x] Add multiple conditions based on `PropertyFilter` component;
- [x] Add condition grouping;

#### Filter appearance
- [x] `ControlsLayout` appearance on different screens;
- [x] `ConditionsLayout` appearance on different screens;

#### XML
- [x] Add `<properties/>` XML element;
- [x] Add `<groupFilter/>` XML element;
- [x] Add ability to define Filter in XML* **(Optional)**;

### Test projects
[filter-component-ui.zip](https://github.com/Haulmont/jmix-ui/files/5688300/filter-component-ui.zip)
[filter-component-ui-data.zip](https://github.com/Haulmont/jmix-ui/files/5688792/filter-component-ui-data.zip)

### Filter components
The generic filter component can only work with components that implement the `FilterComponent` interface. If the component is a container for placing multiple filter components, then it needs to implement `LogicalFilterComponent` interface.
The filter component is treated as a query condition - `PropertyFilter -> PropertyCondition`, `LogicalFilterComponent (GroupFilter) -> LogicalCondition`.

#### GroupFilter
The `GroupFilter` component is a composite component that has a `GroupBoxLayout` component as its root container.  This component is needed to combine several conditions into a logical group (AND by default, OR). The `GroupFilter` is used as the root element for the `conditionsLayout`.

#### PropertyFilter
See Haulmont/jmix-ui#29, Haulmont/jmix-ui#171

### Configurations
A configuration is a set of filter components that has a caption and code. The code must be unique within this filter. The `LogicalFilterComponent` is the root element of the configuration.
The configuration does not store a reference to all components, but stores a reference only to the root element (`LogicalFilterComponent`) from which the rest filter components can be obtained.
Configurations can be created at design time or at run time (via filter configuration editor).

#### Design-time configuration
See `DesignTimeConfigurationImpl` class. Such configurations cannot be changed and saved in run-time, but the user can use `FilterCopyAction` that copies all conditions from the design-time configuration to run-time configuration.
`Configuration addConfiguration(String code, @Nullable String caption)` method creates and adds to filter a design-time configuration.
Use `showOnLayout` XML attribute to set the design-time configuration as default for filter.
All design-time configurations are displayed in the `selectConfigurationButton`:
<img width="318" alt="image" src="https://user-images.githubusercontent.com/35256248/101496487-3f464180-3983-11eb-8bee-aff7529dfe30.png">

```
<filter id="filter"
        dataLoader="testChildEntitiesDl">
    <properties include=".*"/>
    <configurations>
        <configuration code="test_configuration" caption="Test Configuration 1 (AND)" operation="AND">
            <propertyFilter property="testName"
                            operation="ENDS_WITH"
                            operationEditable="false"/>
            <groupFilter operation="OR">
                <propertyFilter property="testInt"
                                operation="EQUAL"
                                operationCaptionVisible="false"/>
                <propertyFilter property="testDecimal"
                                operation="LESS_OR_EQUAL"
                                captionPosition="TOP"/>
            </groupFilter>
        </configuration>
        <configuration code="test_configuration_2" caption="Test Configuration 2 (OR)" operation="OR">
            <propertyFilter property="testName"
                            operation="ENDS_WITH"
                            operationEditable="false"/>
            <propertyFilter property="testDecimal"
                            operation="LESS_OR_EQUAL"
                            captionPosition="TOP"/>
        </configuration>
    </configurations>
</filter>
```
#### Run-time configuration
See `RuntimeTimeConfigurationImpl`. Such configurations are created by the user in run-time and can be saved and modified.

### Conditions
A condition is a filter component that is not initially added to any of the configurations, but the user can select this component in the `AddConditionScreen` in the **Conditions** section and add it to the run-time configuration.
```
<filter id="filter"
        dataLoader="testChildEntitiesDl">
    <properties include=".*"/>
    <conditions>
        <propertyFilter property="testTime"
                        operation="EQUAL"
                        operationEditable="true"
                        caption="Test time condition"/>
    </conditions>
</filter>
```

### Actions
Now, the `Filter` component implements `ActionsHolder` interface. All actions will be added to the `settingsButton` PopupButton.
<img height="250" alt="image" src="https://user-images.githubusercontent.com/35256248/101454734-e1960300-394a-11eb-9a33-c517e64bdef9.png">

The framework loads a set of default actions for the filter, depending on the connected modules:
* ui module
  * `FilterEditAction` (**filter_edit**)
  * `FilterCopyAction` (**filter_copy**)
  * `FilterClearValuesAction` (**filter_clear_values**)
* ui-data module
  * `FilterSaveAction` (**filter_save**)
  * `FilterSaveWithValuesAction` (**filter_save_with_values**)
  * `FilterSaveAsAction` (**filter_save_as**)
  * `FilterEditAction` (**filter_edit**)
  * `FilterRemoveAction` (**filter_remove**)
  * `FilterCopyAction` (**filter_copy**)
  * `FilterMakeDefaultAction` (**filter_make_default**)
  * `FilterClearValuesAction` (**filter_clear_values**)

User can override default actions in XML or in JAVA:
```
<filter id="filter1" dataLoader="testChildEntitiesDl">
    <properties include=".*"/>
    <actions>
        <action id="addCondition" type="filter_add_condition"/>
        <action id="edit" type="filter_edit"/>
    </actions>
</filter>
```
```
filter.removeAllActions();
FilterAction filterAction = actions.create(FilterAddCondition.class);
filterAction.setFilter(filter);
filter.addAction(filterAction);
```

**filter_save** - saves changes to current filter configuration.
**filter_save_with_values** - saves changes to the current filter configuration using the values in inner filter components as filter default values. (*Not yet implemented*)
**filter_save_as** - saves current filter configuration under new code and caption;
**filter_edit** - edits current run-time filter configuration (opens `FilterConfigurationEdit` screen). Disabled for design-time configurations.
**filter_remove** - removes current run-time filter configuration. Disabled for design-time configurations.
**filter_copy** - copies all conditions from design-time configuration to run-time configuration;
**filter_make_default** - makes the filter configuration default for this screen. The filter will be automatically displayed on the filter panel when the screen is opened. Takes precedence over `showOnLayout` attribute of design-time configurations. (*Not yet implemented*)
**filter_clear_values** - clears the filter condition values.
**filter_add_condition** - adds condition to current filter configuration. The **addCondition** `LinkButton` has this action by default.

### AddConditionScreen
* **Properties** section is defined using the `<properties/>` XML element. See `PropertiesFilterPredicate` class.
  * include – required attribute. It contains a regular expression, which should match an entity attribute name.
  * exclude – contains a regular expression. If an attribute matches the expression, it will be excluded from previously included (using include).
  * excludeProperties – contains a comma-separated list of property paths that should be excluded from filtering. As opposed to exclude, it supports traversing the entity graphs, for example: customer.name.
  * excludeRecursively - defines if an attribute from excludeProperties should be excluded recursively for the whole object graph. If true, an attribute and all its nested attributes with the same name will be excluded.
* **Conditions** section is defined using the `<conditions/>` XML element.
* **Configurations** section is defined using the `<configurations/>` XML element.
<img height="350" alt="image" src="https://user-images.githubusercontent.com/35256248/101550640-18126300-39c9-11eb-8bc6-114d75e05cf5.png">

### Filter component registration
See `FilterComponentRegistration` class. The `FilterComponentRegistration` class has the following attributes:
* `componentClass` (required) - filter component class, must extend from `FilterComponent` class;
* `modelClass` (required) - non-persistent entity class that stores the state of the filter component, must extend from `FilterCondition` class. The model class is used to save filter component state in DB and is used to display and change the state of the filter component at runtime;
* `converterClass` (required) - a converter class for converting between a component and a model must implement the FilterConverter interface.
* `editorScreenId` (optional) - ID of the model edit screen. If no identifier is specified then the default identifier (`modelName.edit -> PropertyFilterCondition.edit`) will be used.
`PropertyFilter` registration example:
```
    @Bean
    public FilterComponentRegistration registerPropertyFilterComponent() {
        return FilterComponentRegistrationBuilder.create(PropertyFilter.class,
                PropertyFilterCondition.class,
                PropertyFilterConverter.class)
                .withEditScreenId("ui_PropertyFilterCondition.edit")
                .build();
    }
```
All registered filter components are displayed in a `PopupButton` on the `AddConditionScreen` so that the user has the opportunity to create a filter component in runtime. Pressing the button will open the editor screen for the selected filter component.
<img width="318" alt="image" src="https://user-images.githubusercontent.com/35256248/101546072-abe03100-39c1-11eb-9106-1d026ccfaffd.png">

This method of registering filter components is convenient because we can register the filter components in different modules. And also the user can replace the filter component registered in the jmix framework with his own implementation by specifying the `@Order` annotation (for example, to expand the set of model attributes saved by the filter).

See an example of expanding the supported values for a `PropertyFilter` in ui-data test project

**Comment by glebfox** [comment]
Consider using `CompositeComponent` and `ResponsiveGridLayout` as a root container in this case.

**Comment by alexbudarov** [comment]
Ability to sort entity option values in the filter lookupPickerField:
https://www.cuba-platform.ru/discuss/t/sortirovka-v-pole-filtra-vypadayushhij-spisok/5129/3
