### ISSUE TITLE
AfterCommitEvent : add “windowClosing” information

### ISSUE THREAD

**Issue by alexbudarov** [Haulmont/jmix-ui#163]
https://www.cuba-platform.com/discuss/t/aftercommitevent-add-windowclosing-information/13986

> In a Screen, when reacting to AfterCommitChangesEvent it would be useful to know if the screen is about to close - i.e we are in commitAndClose() or closeWithCommit().
> 
> In my project screen I have an “History” tab displaying EntityLogItem entries, the screen uses extendedEditWindowActions so with Save button (w/out closing), and OK button (save then close).
> 
> On Save, I would like to reload history items in order to reflect changes in History tab after commit. On OK, I don’t bother if the screen is closing. On Cancel I don’t bother of course.
> 
> This could be a simple boolean in AfterCommitChangesEvent, e.g “screenClosing”.

**Comment by glebfox** [comment]
The current implementation uses call chains, e.g.: 

```
public OperationResult closeWithCommit() {
        return commitChanges()
                .compose(() -> close(WINDOW_COMMIT_AND_CLOSE_ACTION));
    }
```

Both `commit` and `commitAndClose` use the same `commitChanges()` method to commit changes, which shouldn't care about particular circumstances of a commit as well as the `AfterCommitChangesEvent`. 

The described case can be easily implemented in the particular Editor, e.g.:

```
@Override
protected void commit(Action.ActionPerformedEvent event) {
    commitChanges()
            .then(() -> {
                commitActionPerformed = true;
                
                // add custom code
                notifications.create()
                        .withCaption("Committed")
                        .show();
            });
}
```

**Comment by alexbudarov** [comment]
@glebfox 
OK, if AterCommitChangesEvent isn't suitable, then we can provide another event "CommitedButWindowNotClosed".
We had such extention point in CUBA 6 - it was postInit() method!

Now there is no extension point for logic "refresh my screen after commit".
This is an API regression since CUBA 6.
