### ISSUE TITLE
Rename userLogin attribute in ui-data module to username

### ISSUE THREAD

**Issue by GlebDurygin** [Haulmont/jmix-ui#178]
The `UiSetting` and `UiTablePresentation` entities have `userLogin` attribute and `USER_LOGIN` column. But `BaseUser` class has a `username` attribute instead of `userLogin`.

**Comment by Flaurite** [comment]
Commit jmix-ui [cff1f5f](https://github.com/Haulmont/jmix-ui/commit/cff1f5f92a78e9cdc7069070fc1308836608f3f4).

**Comment by Flaurite** [comment]
Commit [Haulmont/jmix-cuba@02160e8](https://github.com/Haulmont/jmix-cuba/commit/02160e841796d60620e63074cf887f90932ac504)
