### ISSUE TITLE
[Helium] Implement missing styles

### ISSUE THREAD

**Issue by GlebDurygin** [Haulmont/jmix-ui#183]
See **StylesContainersSample** in **jmix-sampler**.
```
            <groupBox caption="GroupBox"
                      width="270px">
                <groupBox expand="content1"
                          height="200px"
                          showAsPanel="true"
                          stylename="borderless"
                          width="230px">
                    <hbox expand="caption"
                          stylename="v-panel-caption"
                          width="100%">
                        <label id="caption"
                               value="panel borderless"/>
                        <button align="MIDDLE_RIGHT"
                                icon="SAVE"
                                stylename="borderless icon-only"/>
                    </hbox>
                    <label id="content1"
                           value="msg://io.jmix.sampler.screen.ui.predefinedstyles.styles/loremIpsum"
                           width="210px"/>
                </groupBox>
            </groupBox>
```

Actual behavior:
![image.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/b0ba53ed-d838-4bb2-96e2-d889bc402236)

Expected behavior:
![image.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/2b48bee0-5951-4f31-ba2d-ee9e3d52393a)

#### "well" style:
```
<groupBox caption="WELL"
          width="200px"
          height="200px"
          showAsPanel="true"
          stylename="well">
    <label value="content content content"/>
</groupBox>
```
**AR**
![image](https://user-images.githubusercontent.com/22093943/115723614-36359a00-a391-11eb-8726-75f5ba28d1d9.png)

**ER**
![image](https://user-images.githubusercontent.com/22093943/115723820-6715cf00-a391-11eb-9b95-714abefddcef.png)

#### "light" style
As view of GroupBox in Helium is changed we need to think how to adapt "light" style. Because in Halo/Hover theme it looks as follows:
![image](https://user-images.githubusercontent.com/22093943/115724181-c673df00-a391-11eb-9f5e-d5db495e59c6.png)

## Solution 

The following styles have been supported:

**SplitPanel** 

* `splitter-large` (former `large`) - https://demo.jmix.io/sampler/#main/sample?id=styles-splitpanel

**Containers**

* `borderless` - GroupBox, Accordion
* `well` - GroupBox
* `v-panel-caption` - HBox

**Button**

* `icon-align-top` - https://demo.jmix.io/sampler/#main/sample?id=styles-button

**Fields**

* `borderless` - ComboxBox, DateField, TimeField, TextField, TextArea, ResizableTextArea, TagField, ValueField and its inheritors

**Fixed bugs reported in the addon repo**

* https://github.com/cuba-platform/helium-theme/issues/49
* https://github.com/cuba-platform/helium-theme/issues/46

P.S GroupBox `light` and `classic` will be implemented in a separate issue

**Comment by owlet1997** [comment]
TimeField doesn't support 'borderless' style:
```
<timeField stylename="borderless"/>
```
![image](https://user-images.githubusercontent.com/45730069/119984337-57ae2500-bfd2-11eb-9c66-bf9c32ec8493.png)

**Comment by owlet1997** [comment]
DataGrid without activated style "small':
![image](https://user-images.githubusercontent.com/45730069/119988341-0c4a4580-bfd7-11eb-91d2-f485f7b857bf.png)
DataGrid with activated style "small':
![image](https://user-images.githubusercontent.com/45730069/119988403-2421c980-bfd7-11eb-8b74-5d5017ec2732.png)
Buttons have been recized but fields have not

**Comment by glebfox** [comment]
Due to VAADIN implementation DataGrid, TreeDataGrid and Tree can't adapt to size presets, hence inline editors also remain default size as well as fields within it
