### ISSUE TITLE
Excel export creates junk cell content for byte[] fields

### ISSUE THREAD

**Issue by alexbudarov** [Haulmont/jmix-ui#184]
I don't know how it worked in CUBA, but in Jmix excelExport action exports byte[] columns as .toString() content.

See generated excel file:
[Language.xlsx](https://github.com/Haulmont/jmix-ui/files/5630369/Language.xlsx)
![image](https://user-images.githubusercontent.com/6158807/100894656-2991d180-34d6-11eb-8a17-69bb618c901b.png)

In controller I have generated column that displays byte[] as Icon.

Not sure what should be printed in the Excel file. Just empty cell maybe?

**Comment by glebfox** [comment]
Print `<bytes>`instead
