### ISSUE TITLE
Can't use localized message for bean validations

### ISSUE THREAD

**Issue by alexbudarov** [Haulmont/jmix-ui#201]
Project: attached
[bvalm.zip](https://github.com/Haulmont/jmix-ui/files/5702581/bvalm.zip)

see Animal entity - two attributs.

I tried two different formats but both of them don't work:
```
    @Length(message = "msg:///animal.name.length", min = 3)
    @InstanceName
    @Column(name = "NAME", nullable = false)
    @NotNull
    private String name;

    @Positive(message = "msg://com.company.bvalm.entity/animal.weight.positive")
    @Column(name = "WEIGHT")
    private Double weight;
```

main message pack:
```
animal.name.length=Name must be at least 3 symbols
com.company.bvalm.entity/animal.weight.positive=Weight must be positive
```

![image](https://user-images.githubusercontent.com/6158807/102347629-18f35800-3fba-11eb-87ae-d44a5395bb4c.png)

![image](https://user-images.githubusercontent.com/6158807/102347678-2b6d9180-3fba-11eb-8648-06123eab2684.png)

**Comment by andreysubbotin** [comment]
Place the message in a localized messages pack and use the following format to specify the message in an annotation: `{msg://message_pack/message_key}` or simply `{msg://message_key}` (for entities only).

CUBA Documentation: https://doc.cuba-platform.com/manual-7.2/bean_validation_constraints.html#bean_validation_messages
