### ISSUE TITLE
JmixWebJarsHandler does not find WebJar resources

### ISSUE THREAD

**Issue by m-orlova** [Haulmont/jmix-ui#204]
WebJar resources that are placed in classpath can not be found by JmixWebJarsHandler:
JmixWebJarsHandler handles the requests with path started with prefix "/webjars/". But when resource is searched in the classpath (see JmixWebJarsHandler#getClassPathResourceUrl) the path is translated to WebJar path with other prefix "VAADIN/webjars/" (see WebJarResourceResolver#translateToWebJarPath). As a result the prefix is not removed from path and resource is not found by WebJarResourceResolver.

**Comment by glebfox** [comment]
Can't reproduce
