### ISSUE TITLE
The screen with Data Grid hides the buttons as default

### ISSUE THREAD

**Issue by lovtsovaik** [Haulmont/jmix-ui#207]
### Environment
Jmix framework version: 0.2.0

### Description of the bug or enhancement

1. Open the project [scrwiz.zip](https://github.com/Haulmont/jmix-ui/files/5714269/scrwiz.zip)
2. Run the application
3. Open Application -> Numbers DataGrid screen
4. Scroll up

ER: Scroll is not needed
AR: The table header is at the top of the screen dy default, despite the presence of buttons and pagination above
![image](https://user-images.githubusercontent.com/73226373/102586848-49ef9c00-4124-11eb-9144-e8835e3809ab.png)

This happens when the count of rows is enough to fill the screen

**Comment by glebfox** [comment]
DataGrid has `AUTO` height and it takes more space than screen height, as a result the screen scroll appears.
