### ISSUE TITLE
Display URI attributes as file name in table components

### ISSUE THREAD

**Issue by alexbudarov** [Haulmont/jmix-ui#209]
Motivation: see JST-382 Jmix Studio ticket.

We want the **uploaded file** fields (byte array and URI) to be easily displayable in browser tables and editor forms.
We will also scaffold fields / columns in Studio when generating screens by entity.

For editor forms the task is easy - just use fileUploadField / fileStorageUploadField.

For browser table there are problems:
- there is no good way to display byte[] in table column
- for URI - you could display it as a file name (obtain it from the file storage). But at the moment table displays them just as String content:
![image](https://user-images.githubusercontent.com/6158807/102634609-7d094e00-416b-11eb-9041-863c4ed8b139.png)

**Suggestion**
Add implicit formatter for table columns - display URI as file name.

**Comment by glebfox** [comment]
Not actual
