### ISSUE TITLE
The Russian alert text on email validation

### ISSUE THREAD

**Issue by lovtsovaik** [Haulmont/jmix-ui#217]
### Environment
Jmix framework version: 0.2.0

### Description of the bug or enhancement

1. Open the project [planner.zip](https://github.com/Haulmont/jmix-ui/files/5733573/planner.zip)
2. Run the application
3. Open "Talk and Speakers" -> "Speaker browser"
4. Create a new speaker
5. Fill names
6. Fill Email with wrong data (without `@`)
7. Click OK

ER: The standard text of alert in English
AR: The Russian text, although this text is not in the message pack, and in general there is no Russian localization in the project.
The same in tooltip.

![image](https://user-images.githubusercontent.com/73226373/102964923-32d6f280-4506-11eb-99cb-57e6c6d596a3.png)
![image](https://user-images.githubusercontent.com/73226373/102965471-52224f80-4507-11eb-8492-196e215af155.png)

The bug can be found when passing the Quick Start

----

**Upd:** Depends on browser locale

**Comment by glebfox** [comment]
Seems that https://github.com/Haulmont/jmix-ui/issues/201 also resolves this issue.

**Comment by lovtsovaik** [comment]
fixed
