### ISSUE TITLE
[Drawer] implement size styles

### ISSUE THREAD

**Issue by glebfox** [Haulmont/jmix-ui#220]
### How to test
1. Add to your `<drawer>` element in the `main-screen.xml` styles:
   - `<drawer id="drawer" ... stylename="large">` - the text of SideMenu, TimeZoneIndicator and footer elements should be enlarged.
   - `<drawer id="drawer" ... stylename="small">` - the text of SideMenu, TimeZoneIndicator and footer elements should be reduced.

**Comment by lovtsovaik** [comment]
Implemented for Helium theme
