### ISSUE TITLE
[TablePresentations] support user substitution

### ISSUE THREAD

**Issue by glebfox** [Haulmont/jmix-ui#223]
### Changes
If user (e.g. admin) logged in by substituted user (user_1):
- presentations will be loaded for the substituted user (user_1);
- new presentations will be saved for the substituted user (user_1).

### QA
Check above cases.

**Comment by konyashkina** [comment]
_Tested on_
Jmix version: 1.1.0-SNAPSHOT
Jmix Studio plugin version: 1.1.SNAPSHOT3625-212
IntelliJ version: IntelliJ IDEA 2021.2.2 (Ultimate Edition)
