### ISSUE TITLE
[TimeZoneIndicatorImpl] Implement missing functionality

### ISSUE THREAD

**Issue by glebfox** [Haulmont/jmix-ui#242]
See TODO

Requires `TimeZones` bean.

### QA
In the side menu of MainScreen time zone should be visible:
![image](https://user-images.githubusercontent.com/22093943/107606215-dc0cb000-6c4e-11eb-9834-86a93416a169.png)

**Comment by skatova** [comment]
In the side menu of MainScreen time zone is not centered but on the left
![image](https://user-images.githubusercontent.com/53561930/107647501-a68ab580-6c94-11eb-9799-9a860511e65c.png)

**Comment by Flaurite** [comment]
The problem will be fixed in this issue: [Haulmont/jmix-ui#308](https://github.com/Haulmont/jmix-ui/issues/308)
