### ISSUE TITLE
Logout leads to 404 exception if contextPath is defined

### ISSUE THREAD

**Issue by Flaurite** [Haulmont/jmix-ui#267]
### Steps to reproduce
1. Create new Jmix project;
2. Define the following properties:
```
server.servlet.contextPath=/mypath
```
3. Launch the app
4. Try to login and logout.

**AR**
![image](https://user-images.githubusercontent.com/22093943/105452639-19a59b00-5c98-11eb-962c-1f57e21a4217.png)

**Comment by owlet1997** [comment]
```
Caused by: java.sql.SQLSyntaxErrorException: user lacks privilege or object not found: PERSISTENT_LOGINS in statement [delete from persistent_logins where username = ?]
```
happened because there was dropping table 'PERSISTENT_LOGINS' in automatic generated script in com/company/test/liquibase/changelog/2021/02/10-010-8ebe6561.xml
![image](https://user-images.githubusercontent.com/45730069/107499160-0ce8d880-6bae-11eb-9aae-a54221072230.png)
