### ISSUE TITLE
SimplePagination in the table/datagrid should be aligned to the right

### ISSUE THREAD

**Issue by Flaurite** [Haulmont/jmix-ui#278]
### Description
If there is no enough space for SimplePagination it will resize as follows:
![image](https://user-images.githubusercontent.com/22093943/105986348-400f7000-60b6-11eb-80f8-0111a5edcb5b.png)

But it would be better to resize it like this:

![image](https://user-images.githubusercontent.com/22093943/105986732-bc09b800-60b6-11eb-9ff0-e37bcdbc9a3a.png)

**Comment by DartVerder** [comment]
Fixed on
Jmix version: 1.0.0-SNAPSHOT
Jmix Plugin version: 1.0.SNAPSHOT2622-202
Intellij IDEA 2020.3.2 build 203.7148.57
