### ISSUE TITLE
Users are confused by the presence of some methods

### ISSUE THREAD

**Issue by sukhova** [Haulmont/jmix-ui#279]
Here there are some cases:

`EntityComboBox`:
I want to handle the user input. What handler or event should I choose? I use the Studio. And I am offered a choice:
1) `newOptionHandler` with the "Sets the handler that is called when user types a new item." description.
2) `FieldValueChangeEvent` with the "The event that is fired when a user inputs value manually." description.

I chose the `FieldValueChangeEvent`, launched the application, and there was a `java.lang error.UnsupportedOperationException`

As it turned out, I had to choose `newOptionHandler`.

`EntityPicker`:
In the studio, a `LookupSelectHandler` is available for the `EntityPicker` component. But in fact, this handler does not work.

And I don't check all the handlers/events for each component.

Is it possible to do something so that the user can intuitively, using only the Studio, understand which handlers can be used and which can not?

**Comment by glebfox** [comment]
add exclude annotation to such methods
