### ISSUE TITLE
Support settings for Pagination and SimplePagination components

### ISSUE THREAD

**Issue by Flaurite** [Haulmont/jmix-ui#290]
### Changes
`SimplePagination` and `Pagination` can save `ItemsPerPage` value. 
![image](https://user-images.githubusercontent.com/22093943/109971961-365dd580-7d10-11eb-9e09-096a033c2cc9.png)

### For QA
To save settings add `screenSettings` facet with `auto="true"` and assign `id` to the pagination component.

1. Check that Pagination can save `null` and other values;
2. Check that SimplePagination in the table and out of the table can save number values. (There is an issue with null value in SimplePagination, see [Haulmont/jmix-ui#366](https://github.com/Haulmont/jmix-ui/issues/366));

**Comment by owlet1997** [comment]
parameter `itemsPerPageDefaultValue` of component `pagination` can be used only when component has no `id` attribute
