### ISSUE TITLE
Cannot create database on mysql

### ISSUE THREAD

**Issue by alexbudarov** [Haulmont/jmix-ui#301]
See Studio ticket JST-651

- Open attached project
[dbmysql.zip](https://github.com/Haulmont/jmix-ui/files/5952358/dbmysql.zip)

- Specify valid mysql database credentials
- Try to re-create database (or update empty database)

Liquibase error occurs:
```
2020-12-09 20:07+0000) Unexpected error running Liquibase: Validation Failed: 
1 changes have validation failures 
columnDataType is required for renameColumn on mysql, 
io/jmix/uidata/liquibase/changelog/001-ui-data.xml::4::ui-data 
For more information, please use the --logLevel flag
```

**Comment by lovtsovaik** [comment]
The same problem with MariaDB:
project [dbmar.zip](https://github.com/Haulmont/jmix-ui/files/5957170/dbmar.zip)

`Unexpected error running Liquibase: Validation Failed: 1 changes have validation failures columnDataType is required for renameColumn on mariadb, io/jmix/uidata/liquibase/changelog/001-ui-data.xml::4::ui-data For more information, please use the --logLevel flag
`

**Comment by Flaurite** [comment]
The main reason is fixed, but there is another issue that does not allow you to login: [Haulmont/jmix-data#44](https://github.com/Haulmont/jmix-data/issues/44)

**Comment by lovtsovaik** [comment]
For QA: also check generated scripts for MySQL and MariaDB in entity information window (see https://github.com/Haulmont/jmix-ui/issues/64)
