### ISSUE TITLE
Entity log attribute table is empty

### ISSUE THREAD

**Issue by dtaimanov** [Haulmont/jmix-ui#302]
Jmix version: 0.3.0-SNAPSHOT

Entity Log Attributes table shows empty rows
![изображение.png](https://images.zenhubusercontent.com/5ed6636766d0991824e90fb6/49d7f83f-6e70-4f63-ad86-1c6b02379aa0)

#### Steps:
1. Create new Jmix project
2. add dynattr and audit addons in build.gradle:
```
    implementation "io.jmix.dynattr:jmix-dynattr-starter"
    implementation "io.jmix.dynattr:jmix-dynattr-ui-starter"

    implementation "io.jmix.audit:jmix-audit-starter"
    implementation "io.jmix.audit:jmix-audit-ui-starter"
```
3. Create entity and setup auto logging for all it's attributes
![изображение.png](https://images.zenhubusercontent.com/5ed6636766d0991824e90fb6/98d5fd8b-db09-4371-b353-c21c844b65ae)
4. Create several instances
5. Open entity log screen and select one of records in left table
**ER:**
Right table contains attribute changes
**AR:**
Right table contains empty rows

**Comment by andreysubbotin** [comment]
Fixed in Haulmont/jmix-audit#16
