### ISSUE TITLE
[UserIndicator] Implement missing functionality

### ISSUE THREAD

**Issue by glebfox** [Haulmont/jmix-ui#309]
## Solution 

Currently, there is no User Substitution functionality, so the User indicator can only display the current use caption.

See: https://github.com/haulmont/jmix-security/issues/30 and https://github.com/haulmont/jmix-ui/issues/241

**Comment by natfirst** [comment]
For QA: see information in docs https://doc.cuba-platform.com/manual-latest/search.jsp?searchTerms=userIndi&caseSensitive=no
