### ISSUE TITLE
Component's caption is not displayed if component is placed into Splitpanel

### ISSUE THREAD

**Issue by owlet1997** [Haulmont/jmix-ui#313]
**Enviroment:**
0.3.0-SNAPSHOT

**TC:**
1. Create new project
2. Add VerticalSplitPanel or HorizontalSplitPanel to the XML-descriptor of any screen
3. Add component (TextField, TagField, EntityPicker etc) with caption into `<split>` tag
4. Run application

**AR: **
component's caption  is not displayed
**ER: **
component's caption should be displayed 
![image.png](https://images.zenhubusercontent.com/5ffd7dc3b256a97bde8addb9/747e7105-ea7f-4d6c-ae18-e048f52e63a5)
![image.png](https://images.zenhubusercontent.com/5ffd7dc3b256a97bde8addb9/98bacdd2-7e3e-4475-b7dd-e41759fd5c63)

**Comment by glebfox** [comment]
Never worked. `AbstractSplitPanelConnector` (Vaadin base class) doesn't implement the `updateCaption(ComponentConnector component)` method.
