### ISSUE TITLE
Buttons that determine the order of filter components in a Filter do not work

### ISSUE THREAD

**Issue by GlebDurygin** [Haulmont/jmix-ui#323]
Related to Haulmont/jmix-ui#196

1) Create a configuration with two conditions;
![image.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/bb5ed6e1-72bb-405b-88a3-d631447cb930)
2) Click on `filter_edit` action;
3) Click on the first condition;
![image.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/a3ebf63b-8e21-4468-a66e-278422e1a262)
4) Click on the `moveDown` button;
![image.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/deb6d04e-e154-4969-9a23-5586d14e401d)
5) Save the configuration

* Expected behavior:
The configuration should save the order of the filter component from the editor

* Actual behavior:
![image.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/bb5ed6e1-72bb-405b-88a3-d631447cb930)

**Comment by maistrenkoIulia** [comment]
TC:
try  to remove condition from config editor>ok
open  config editor
AR:
condition hasn`t been removed

![image](https://user-images.githubusercontent.com/66992566/108967397-e68c6800-7698-11eb-9d8f-81cbd167f9d7.png)

**Comment by maistrenkoIulia** [comment]
Move up/move down options should be added to context menu

![image](https://user-images.githubusercontent.com/66992566/109122707-6c281a80-7762-11eb-97d3-4ecc7fef9dde.png)

**Comment by GlebDurygin** [comment]
> Move up/move down options should be added to context menu

MoveUp and MoveDown actions cannot be added to the context menu because they do not have captions.

**Comment by maistrenkoIulia** [comment]
fixed
