### ISSUE TITLE
Implement design-time roles from CUBA

### ISSUE THREAD

**Issue by alexbudarov** [Haulmont/jmix-ui#330]
In CUBA we had several design-time roles for filters and folders.

![image](https://user-images.githubusercontent.com/6158807/108736970-8fc54800-754b-11eb-9606-d20b38fac8c3.png)
![image](https://user-images.githubusercontent.com/6158807/108737002-9653bf80-754b-11eb-9892-ee7aaffae484.png)

**Comment by glebfox** [comment]
Will be implemented in separate issues, e.g. https://github.com/Haulmont/jmix-ui/issues/274
