### ISSUE TITLE
Add method InputParameter.withRequiredMessage()

### ISSUE THREAD

**Issue by alexbudarov** [Haulmont/jmix-ui#331]
Add functionality to InputDialog to set requiredMessage for the parameter.
Currently io.jmix.ui.app.inputdialog.InputParameter already has withRequired() method.

forum topic: https://www.cuba-platform.com/discuss/t/inputparameter-set-required-message/14787

----
### Changes
Added the following methods to `InputParameter` class:
- `getRequiredMessage()`
- `withRequiredMessage()`

Java example:
```
dialogs.createInputDialog(this)
        .withParameter(InputParameter.stringParameter("nameField")
                .withRequired(true)
                .withRequiredMessage("Name field is required"))
        .show();
```

XML example:
```
<inputDialog id="nameFormDialog">
    <parameters>
        <stringParameter id="nameField"
                         required="true"
                         requiredMessage="msg://nameField.requiredMessage"/>
    </parameters>
</inputDialog>
```

### For QA
1. Check feature using  XML facet.
2. Check all parameters excluding boolean (it does not have required feature)
3. Check that "Component Inspector" has `requiredMessage` field for all types excluding boolean.

**Comment by imorenov94** [comment]
Unavailable creating a local message from component inspector
