### ISSUE TITLE
Incorrect work of setFocusable method

### ISSUE THREAD

**Issue by sukhova** [Haulmont/jmix-ui#333]
1) Create buttons:
```
<button id="helloButton2" focusable="true"/>
<button id="helloButton3" focusable="false"
                    caption="msg://button.caption"/>
<button id="helloButton4"
                    caption="msg://button.caption"/>
```

**AR**:
`helloButton2` is not focused by TAB key
`helloButton3` is not focused by TAB key
`helloButton4` is focused by TAB key

### Solution

* The `setFocusable` method sets tabulator index to **0** if **true** is passed, **-1** otherwise.
* The redundant `focusable` attribute has been removed for button, popupButton, bulrEditor and relatedEntities components. Instead, the `tabIndext` attribute must be used in XML since it's been introduced. 
* CUBA module still has the `focusable` attribute for compatibility purposes.

**Comment by knstvk** [comment]
@sukhova - Did it work in CUBA?

**Comment by sukhova** [comment]
> 
> 
> @sukhova - Did it work in CUBA?

@knstvk No
