### ISSUE TITLE
Unable to add search condition if the entity has a property with the FileRef type

### ISSUE THREAD

**Issue by m-orlova** [Haulmont/jmix-ui#339]
Steps to reproduce:
1. Run the project [fileref.zip](https://github.com/Haulmont/jmix-ui/files/6043005/fileref.zip)
2. Open Application -> FileEntity browser
3. Click on "Add search condition"

AR: 
![image](https://user-images.githubusercontent.com/71265042/109155851-87f2e700-7789-11eb-812c-aea0dee2af43.png)

**Comment by GlebDurygin** [comment]
Fixed in #336
