### ISSUE TITLE
Focused UserIndicator shows outline

### ISSUE THREAD

**Issue by Flaurite** [Haulmont/jmix-ui#340]
### Environment
Browser: Chrome, Opera;
OS: windows 10;

### Steps to reproduce
1. Create and launch new project;
2. Click on UserIndicator label;

**ER**
![image](https://user-images.githubusercontent.com/22093943/109261533-5d506f00-7819-11eb-9625-993a1efc7203.png)

**AR**
![image](https://user-images.githubusercontent.com/22093943/109261499-532e7080-7819-11eb-9c71-5303e4273f18.png)

**Comment by Flaurite** [comment]
Check side and top menu styles.

**Comment by DartVerder** [comment]
Fixed on
Jmix version: 1.0.0-SNAPSHOT
Jmix Plugin version: 1.0.SNAPSHOT2622-202
Intellij IDEA 2020.3.2 build 203.7148.57
