### ISSUE TITLE
Filter configuration name should be unique

### ISSUE THREAD

**Issue by maistrenkoIulia** [Haulmont/jmix-ui#354]
Jmix Studio plugin version: 1.0.SNAPSHOT2581-202
IntelliJ version: IntelliJ IDEA 2020.3.2 (Community Edition)

TC: 
 Create two filter configurations with name Test
ER: validation error
AR: both configurations have been created successfully
![image](https://user-images.githubusercontent.com/66992566/109785932-15b95100-7c26-11eb-801a-4de548368aab.png)

**Comment by GlebDurygin** [comment]
The configuration names can be repeated. Only configuration ids must be unique.
