### ISSUE TITLE
Generic paging component

### ISSUE THREAD

**Issue by Flaurite** [Haulmont/jmix-ui#36]
### Description
There is a RowCount component built-in tables/dataGrid. It has the following limitations:

- it does not contain rows per page setting (currently in filter).
- it cannot be used outside of tables.
- it can be more customizable and contain page buttons.

**Comment by alexbudarov** [comment]
Studio ticket: JST-137

**Comment by glebfox** [comment]
@Flaurite add detailed description (pre docs)
