### ISSUE TITLE
Generate ComboBox component for default value field if JpqlFilter has Boolean parameter class

### ISSUE THREAD

**Issue by GlebDurygin** [Haulmont/jmix-ui#362]
### Minimal reproducible example
1) Create a test screen with Filter
2) Open "Add search condition" dialog
3) Click on "Create JPQL condition" button
4) Select "Boolean" class for `Parameter type` attribute

* Expected behavior 
    The `defaultValueField` is a `ComboBox`.
* Actual behavior 
    The `defaultValueField` is a `CheckBox`.

**Comment by maistrenkoIulia** [comment]
fixed
