### ISSUE TITLE
Change the order of the options in the parameter type field in JpqlFilterConditionEdit

### ISSUE THREAD

**Issue by GlebDurygin** [Haulmont/jmix-ui#369]
#### New order of options (from CUBA):
![image.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/3eaf8e5e-0865-4b95-b809-0ec8a477947a)

**Comment by DartVerder** [comment]
Fixed on
Jmix version: 1.0.0-SNAPSHOT
Jmix Plugin version: 1.0.SNAPSHOT2623-202
Intellij IDEA 2020.3.2 build 203.7148.57
