### ISSUE TITLE
Table/DataGrid top panel does not correctly shrink items

### ISSUE THREAD

**Issue by Flaurite** [Haulmont/jmix-ui#370]
### Description
Due to we started to use CssLayout with `flex`, elements do not correctly shrink (see [Haulmont/jmix-ui#208](https://github.com/Haulmont/jmix-ui/issues/208)).
![simplepaginationbug](https://user-images.githubusercontent.com/22093943/110121908-683a6f00-7dd8-11eb-88a5-79c8a21ba887.gif)

Here we can see where the border lies between SimpePagination and ButtonsPanel:

![image](https://user-images.githubusercontent.com/22093943/110122350-f282d300-7dd8-11eb-8608-f20da0171555.png)

**Comment by DartVerder** [comment]
I think the "rows per page" ComboBox should be moved to the second row when there is not enough space and the button panel is already shrinked. Now simple pagination does not shrink
![shr1](https://user-images.githubusercontent.com/69783839/112824979-457c3d00-909c-11eb-8c6f-d0f1286b9990.png)
![shr2](https://user-images.githubusercontent.com/69783839/112824994-48772d80-909c-11eb-9c1c-45da9694f5dd.png)

**Comment by glebfox** [comment]
The actual fix is to make the Pagination component keep its width, so only buttons area changes its size.
