### ISSUE TITLE
Remove fix for TwinColumn selection after migrating to new Vaadin version

### ISSUE THREAD

**Issue by Flaurite** [Haulmont/jmix-ui#373]
### Description
We have fixed the reorder bug with TwinColumn but Vaadin fixed it in ~ 8.10 version. We should check if it works without our code we need to remove the fix.

See details in [cuba-platform/cuba#2556](https://github.com/cuba-platform/cuba/issues/2556)

**Comment by glebfox** [comment]
It appears that we have to keep our code. There were other fixes as well.
