### ISSUE TITLE
Fix typo in UiDataFilterConfigurationModelFragment

### ISSUE THREAD

**Issue by GlebDurygin** [Haulmont/jmix-ui#378]
Fix typo in UiDataFilterConfigurationModelFragment with Russian locale

#### Example without `ScreenSettingsFacet`
1) Create a screen with `Filter` component
2) Open filter configuration editor

* Actual behavior:
![image](https://user-images.githubusercontent.com/35256248/111278158-acd4ce80-8652-11eb-91c7-b8c1217e86a1.png)

* Expected behavior:
![image](https://user-images.githubusercontent.com/35256248/111280747-9da35000-8655-11eb-93ac-3818d28d296c.png)

#### Example with `ScreenSettingsFacet`
1) Create a screen with `Filter` component
2) Add `<screenSettings auto="true"/>` in `<facets/>` element
3) Open filter configuration editor

* Actual behavior 
![image](https://user-images.githubusercontent.com/35256248/111278447-f7564b00-8652-11eb-8c9e-c12728747ddf.png)

* Expected behavior 
![image](https://user-images.githubusercontent.com/35256248/111431726-90e63100-8715-11eb-8c93-3df9b8b61e0a.png)

**Comment by DartVerder** [comment]
![image](https://user-images.githubusercontent.com/69783839/111457607-dadd1000-8731-11eb-8093-d042ade0aa1e.png)
