### ISSUE TITLE
The entityPicker and listComponent properties of LookupScreen and EditorScreen facets suggest too many components

### ISSUE THREAD

**Issue by lovtsovaik** [Haulmont/jmix-ui#390]
Jmix platform version: 1.0.0-SNAPSHOT
Jmix plugin version 1.0.SNAPSHOT2650-202

**Test case**

1. Create en entity with one-to-one or many-to-one association
2. Create master-detail screen
3. Add `LookupScreen` and `EditorScreen` facets to the screen
4. Select them
5. In Component Inspector look at the list of values in `entityPicker` and `listComponent` properties

**AR** 
there is all components of the screen
<img src="https://user-images.githubusercontent.com/73226373/111629606-e819fd80-880a-11eb-8fa5-87323761b497.png" height="500"/>
<img src="https://user-images.githubusercontent.com/73226373/111629646-f405bf80-880a-11eb-9534-99b4337f27d4.png" height="500"/>

**ER** 
filter components:
- entityPicker property should contain only entityPicker components
- listComponent property should contain the tables / grids (see [doc](https://doc.cuba-platform.com/manual-7.2/gui_EditorScreenFacet.html#gui_EditorScreenFacet_listComponent))

**Comment by glebfox** [comment]
@Gasloff, could you take a look and tell if we can do something in the UI module or is this a Studio problem?

**Comment by Gasloff** [comment]
Ok, I'll check
