### ISSUE TITLE
DialogAction does not support event type class ActionPerformedEvent

### ISSUE THREAD

**Issue by lovtsovaik** [Haulmont/jmix-ui#393]
Jmix platform version: 1.0.0-SNAPSHOT

1. Open project [testui.zip](https://github.com/Haulmont/jmix-ui/files/6164489/testui.zip)
2. Run the app
3. Open Application > Screen

**AR**
Unexpected error occurs:
> DevelopmentException: Target io.jmix.ui.component.ActionsAwareDialogFacet$DialogAction does not support event type class 
io.jmix.ui.action.Action$ActionPerformedEvent

```
io.jmix.core.DevelopmentException: Target io.jmix.ui.component.ActionsAwareDialogFacet$DialogAction does not support event type class io.jmix.ui.action.Action$ActionPerformedEvent
	at io.jmix.ui.sys.UiControllerDependencyInjector.initSubscribeListeners(UiControllerDependencyInjector.java:396)
	at io.jmix.ui.sys.UiControllerDependencyInjector.inject(UiControllerDependencyInjector.java:127)
	at io.jmix.ui.sys.ScreensImpl.createScreen(ScreensImpl.java:211)
	at io.jmix.ui.sys.ScreensImpl.create(ScreensImpl.java:142)
        ...
```

For QA, to full reproduce:

- add inputDialog and OptionsDialog facets
- add actions to them
- generate handlers for this actions

**Comment by glebfox** [comment]
Dialog actions have specific event - `DialogActionPerformedEvent` that is correctly suggested by Studio

<img width="987" alt="Screenshot 2021-03-31 at 13 40 35" src="https://user-images.githubusercontent.com/6077149/113124795-f57db180-9226-11eb-8607-cd21652ed419.png">

**Comment by lovtsovaik** [comment]
Studio ticket: https://youtrack.haulmont.com/issue/JST-1027
