### ISSUE TITLE
Rename simplePagination.nullItemsPerPageOptionVisible → itemsPerPageUnlimitedOptionVisible

### ISSUE THREAD

**Issue by knstvk** [Haulmont/jmix-ui#402]
### Changes
`Pagination`, `SimplePagination` and `SimplePagination` in the DataGrid/Table renamed attribute:
```
nullItemsPerPageOptionVisible → itemsPerPageUnlimitedOptionVisible
```

### For QA
1. Check Java and declarative API: renamed attribute works
2. Add screenSettings facet to the screen:
   ```
   <screenSettings auto="true"/>
   ```
   Define `id` for SimplePagination or Pagination in the screen descriptor and check that the unlimited (null) option can be saved and restored after closing and opening the screen.
   
P.S. Studio issue has been already created.

**Comment by DartVerder** [comment]
if you select unlimited option, displayed value in the checkbox = 10000.(clarified by copying the value)
![image](https://user-images.githubusercontent.com/69783839/112319892-f0b97a80-8cc7-11eb-8928-ad146c5ea8d0.png)
After close and open screen, option not restored. Regardless of the set value, after reopening, the value of items per page is equal to the default (50)
