### ISSUE TITLE
Helium Dark

### ISSUE THREAD

**Issue by glebfox** [Haulmont/jmix-ui#405]
Implement Helium Dark preset

For QA:

CUBA patch:
[sandbox.patch.zip](https://github.com/Haulmont/jmix-ui/files/6434916/sandbox.patch.zip)

[For Jmix] add the following menu item in order to display theme settings screen:
```
<item screen="themeSettingsScreen" caption="Theme Settings"/>
```

**Comment by maistrenkoIulia** [comment]
for Framed TabSheet - NOK
![image](https://user-images.githubusercontent.com/66992566/119386657-e708bf00-bcd8-11eb-8388-c15b4b3de65b.png)

**Comment by maistrenkoIulia** [comment]
verified
