### ISSUE TITLE
Edit, Remove and other standard actions should change their look based on row-level roles

### ISSUE THREAD

**Issue by alexbudarov** [Haulmont/jmix-ui#412]
Example project:
[jrlvl.zip](https://github.com/Haulmont/jmix-ui/files/6221869/jrlvl.zip)

Account entity has link to User:
```
@JmixEntity
@Table(name = "ACCOUNT")
@Entity
public class Account {
// ...
    @JoinColumn(name = "AUTHOR_ID")
    @ManyToOne(fetch = FetchType.LAZY)
    private User author;
}
```

Row-level role restricts update and delete for non-authors:
```
@RowLevelRole
public interface SiteUserRowLevelRole {

    @PredicateRowLevelPolicy(
            entityClass = Account.class,
            actions = {RowLevelPolicyAction.UPDATE, RowLevelPolicyAction.DELETE}
    )
    default Predicate<Account> deckCanBeChanged(CurrentAuthentication currentAuthentication) {
        return deck -> {
            UserDetails details = currentAuthentication.getUser();
            if (details instanceof User) {
                User user = (User) details;
                return user.equals(deck.getAuthor());
            }
            return false;
        };
    }
}
```

**Actual behavior**
Remove permission - doesn't work now (it's a separate bug in security module).
Edit permission - is checked only when the editor screen is committed. Access denied error is shown:
![image](https://user-images.githubusercontent.com/6158807/112841277-5aaf9680-90b1-11eb-9539-d5597a3e46eb.png)
Doesn't look nice!

**Desired behavior**
All standard CRUD actions should on "selected item change" recalculate their properties, also checking row-level role restrictions: enabled and optionally, caption.
E.g.:
* Remove action - should be disabled if row-level role denies REMOVE for the selected entity.
* Edit action - should automatically change its caption to **View** if row-level role denies UPDATE. Should open editor screen in "view" mode when invoked.

**Comment by maistrenkoIulia** [comment]
Remove disabled - ok
Edit disabled - NOK
should chanche caption to view, read-only editor screen should be opened
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT2864-211
IntelliJ version: IntelliJ IDEA 2021.1.1 (Community Edition)
![image](https://user-images.githubusercontent.com/66992566/118089836-dbb0bc00-b3d9-11eb-8aba-b6ec8e0a1d84.png)
[rowlvl.zip](https://github.com/Haulmont/jmix-ui/files/6470793/rowlvl.zip)

**Comment by Desire456** [comment]
Jmix version: 1.0.0-SNAPSHOT

Steps to reproduce
1. Run [attached](https://github.com/Haulmont/jmix-ui/files/6495123/rolessample.zip) project
2. Create new user, add 'system-minimal' and 'users-browse' roles
3. Logout and login as new user
4. Open Users browser, select one and click view button

AR:
Access denied
<img width="274" alt="Снимок экрана 2021-05-17 в 20 05 18" src="https://user-images.githubusercontent.com/49342498/118520791-6a5f6900-b74b-11eb-8dc3-4b86bfadfd43.png">

ER:
Read-only editor screen should be opened

**Comment by bulgakovea** [comment]
@Desire456 
Actually this behavior is expected - the role implementation does not specify access to the entity editor screen.
When you click on "View" application open editor screen in read only mode. Since you don't have access to the editor screen, you get the "Access denied" exception.
Perhaps a more accurate indication of this in the system should be made. @andreysubbotin 
In addition, the SecurityScope should be specified in role implementation.
For example: `@ResourceRole(name = "SampleRole", code = SampleRole.CODE, scope = SecurityScope.UI)`
