### ISSUE TITLE
NullPointerException after invoking export PivotTable to xls

### ISSUE THREAD

**Issue by owlet1997** [Haulmont/jmix-ui#418]
**Enviroment:**
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT2681-202
IntelliJ version: IntelliJ IDEA 2020.3.1 (Community Edition)

**Minimal reproducible example:**
1. Open [attached ](https://app.zenhub.com/files/285297716/d28cb746-a52d-4f2f-8d80-f509103a92a2/download) project -> Run
2. Open screen 'New screen tips'
3. Click 'Export table'

**AR:**
NullPointerException:
![image.png](https://images.zenhubusercontent.com/5ffd7dc3b256a97bde8addb9/b737a95c-36d0-4243-9e01-11165de9eb74)

It occurs because field `filename` in class PivotTableExtensionImpl is not initialized by default depends on pivotTable name (based on [CUBA documentation](https://doc.cuba-platform.com/charts-7.2-ru/pivotTable_extension.html)):
![image.png](https://images.zenhubusercontent.com/5ffd7dc3b256a97bde8addb9/d0712464-e297-471f-bf7d-731d7952ee45)

**ER:**
`Filename` should be initialized by default depends on pivotTable name

**Comment by Flaurite** [comment]
@owlet1997 I've checked this demo project and it turns out that `PivotExcelExporter` is not correctly created. It is a spring bean and should be created as follows:
```
getApplicationContext().getBean(PivotExcelExporter.class, pivotTable);
```
In this case, export to XLS will work as expected.
