### ISSUE TITLE
Incorrect generating fields for arguments in JMX console

### ISSUE THREAD

**Issue by owlet1997** [Haulmont/jmix-ui#423]
**Enviroment:**
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT2706-202
IntelliJ version: IntelliJ IDEA 2020.3.1 (Community Edition)

**Minimal reproducible example:**
1. Create new project 
2. Create new JMX-bean -> add new method with annotation @ManagedOperation, for example:
```
 @ManagedOperation(description = "Get info")
    public String getUserInfo(User user){
        return "This is " + user.getUsername();
    }
```
3. Run app -> open JMX console -> inspect created bean

**AR:**
There is a field of type TextField in operation, unable to choose entity:
![image](https://user-images.githubusercontent.com/45730069/113383176-64c4e400-9394-11eb-95ec-382e07b8de3a.png)
After invoking without entity there is a NullPointerException as expected

**ER:**
Field should be generated depends on type of operation parameters

**Comment by knstvk** [comment]
Only simple types are supported in MBeans.
