### ISSUE TITLE
Routing does not work

### ISSUE THREAD

**Issue by knstvk** [Haulmont/jmix-ui#425]
- Create a new project
- Run it and try to navigate to Users browser and editor

### Solution

* `MainScreen` must contain the Route annotation: `@Route(path = "main", root = true)` - fixed project template, but all existing project must be fixed manually
* `MainScreen` must invoke `screenTools.handleRedirect()` in `void onAfterShow(AfterShowEvent event)` method - fixed project template, but all existing project must be fixed manually
* `io.jmix.ui.AppUI#hasAuthenticatedSession` now returns `false` if the current authentication is represented by `AnonymousAuthenticationToken` in order to enable redirect logic.

**Comment by owlet1997** [comment]
after creating new project @Route annotation in MainScreen controller is highlighted 
![image](https://user-images.githubusercontent.com/45730069/113856136-e2805980-97b1-11eb-99e5-9f8f6d0e2d9f.png)
