### ISSUE TITLE
Aligning labels

### ISSUE THREAD

**Issue by Desire456** [Haulmont/jmix-ui#447]
Test project: [https://app.zenhub.com/files/285297716/ae66b3d9-0024-445c-a3dd-18da1d1f6aa5/download](https://app.zenhub.com/files/285297716/ae66b3d9-0024-445c-a3dd-18da1d1f6aa5/download)
Align property for label doesn't work correctly (don't align).
How to reproduce: run application then open person editor screen.
ER: caption of hbox and label aligned by height.
AR: label placed up than caption of hbox.

**Comment by Flaurite** [comment]
Hi @Desire456,

`Label` is not aligned due to `hbox` has AUTO height. As `Form` component is based on grid layout it calculates size of cells and relative height or width (like "100%") may work incorrectly for components. You can set height in pixels or add CSS style with height like in fields.
