### ISSUE TITLE
DevelopmentException appears using BETWEEN with one filled part in loader query

### ISSUE THREAD

**Issue by owlet1997** [Haulmont/jmix-ui#455]
**Enviroment:**
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT2837-211
IntelliJ version: IntelliJ IDEA 2021.1 (Community Edition)

**TC:**
1. Open [attached](https://app.zenhub.com/files/285297716/59ebe7d9-1775-45de-ad3b-211c761a7ecf/download) project -> run app
2. Open User browser
3. Set any date to 'Date before' field

**AR:**
Unexpected error appears:
![image.png](https://images.zenhubusercontent.com/5ffd7dc3b256a97bde8addb9/e6a30e19-078c-4217-a381-e277f007ff9d)

because  there is BETWEEN keyword is used in loader query:
![image.png](https://images.zenhubusercontent.com/5ffd7dc3b256a97bde8addb9/8a07a1b0-7d88-4efc-915b-61b0c7258822)

when just one field is filled, loader tries to run query

**ER:**
if BETWEEN is used in query and just one field is filled loader should not use this tag <c:jpql>

**Comment by andreysubbotin** [comment]
Couldn't find changes in 1.0

**Comment by andreysubbotin** [comment]
Teamcity build failed: https://teamcity-cuba.haulmont.com/viewLog.html?buildId=3595552&buildTypeId=Jmix_JmixContinuous_JmixData
