### ISSUE TITLE
Theme Settings screen has incorrect styling

### ISSUE THREAD

**Issue by glebfox** [Haulmont/jmix-ui#456]
<img width="493" alt="Screenshot 2021-05-06 at 13 12 05" src="https://user-images.githubusercontent.com/6077149/117272965-bb7a7d80-ae6c-11eb-8765-f5e83952e24f.png">

**Hint:** caused by: Haulmont/jmix-ui#220

**Comment by glebfox** [comment]
Side menu elements have incorrect sizes.

**Before**
<img width="398" alt="Screenshot 2021-05-14 at 12 55 48" src="https://user-images.githubusercontent.com/6077149/118247093-d58f0e00-b4b3-11eb-82f8-1ef6a3d6b303.png">

**After**
<img width="393" alt="Screenshot 2021-05-14 at 12 55 55" src="https://user-images.githubusercontent.com/6077149/118247130-e049a300-b4b3-11eb-9637-caeb5ae68a43.png">

**Comment by maistrenkoIulia** [comment]
verified
