### ISSUE TITLE
Use config instead of theme properties to manage Helium settings

### ISSUE THREAD

**Issue by glebfox** [Haulmont/jmix-ui#457]
Port: https://github.com/cuba-platform/helium-theme/issues/27

## Solution

Helium properties were moved from helium-theme.properties to application.properties, i.e. they were converted from theme properties to app properties. As a result, the UiThemeProperties class has been introduced.

* `jmix.ui.theme.modes` - the list of available theme modes, i.e. color presets. Default: **light, dark**.
* `jmix.ui.theme.defaultMode` - the name of color preset that has no additional style class name. Default: **light**. Note: can’t be changed without corresponding changes in styles.
* `jmix.ui.theme.defaultModeToUse` - the name of color preset to be used if no other settings are available. Either cookie or user settings obtained from `UserSettingService` have precedence over this value.
* `jmix.ui.theme.sizes` - the list of available theme size presets. Default: **small, medium, large**.
* `jmix.ui.theme.defaultSize` - the name of size preset that has no additional style class name. Default: **medium**. Note: can’t be changed without corresponding changes in styles.
* `jmix.ui.theme.defaultSizeToUse` - the name of size preset to be used if no other settings are available. Either cookie or user settings obtained from `UserSettingService` have precedence over this value.

**Breaking changes** 

`jmix.ui.theme` property moved from `UiProperties` class to `UiThemeProperties` class and renamed to `jmix.ui.theme.name`.

**For QA**: Make sure the above properties are applied if placed in the `application.properties` file.

**Comment by maistrenkoIulia** [comment]
verified
