### ISSUE TITLE
Hot deploy for menu configuration

### ISSUE THREAD

**Issue by alexbudarov** [Haulmont/jmix-ui#464]
- create Jmix app
- run application
- create new browser screen, or otherwise edit menu configuration. Studio prints messages about copying updated files to conf.
- relogin in Vaadin UI

Expected:
Updated menu configuration is used

Actual:
Menu configuration isn't updated.

Studio ticket: https://youtrack.jmix.io/issue/JST-506

**Comment by andreysubbotin** [comment]
Fixed in Haulmont/jmix-core#152.
To update messages create an empty file with the name `io.jmix.ui.menu.MenuConfig#reset` in `${jmix.core.tempDir}/triggers` directory.
By default `${jmix.core.tempDir}` equals to `.jmix/temp`
