### ISSUE TITLE
Hot deploy for messages in message pack

### ISSUE THREAD

**Issue by alexbudarov** [Haulmont/jmix-ui#465]
- create Jmix app
- run application
- open messages pack in Studio
- change any message, e.g. one of branding messages on the main or login screen. Studio prints message about copying updated file to conf.
- relogin in Vaadin UI

Expected:
Updated caption is used

Actual:
Caption isn't updated.

Studio ticket: https://youtrack.jmix.io/issue/JST-521

**Comment by andreysubbotin** [comment]
Fixed in Haulmont/jmix-core#152.
To update messages create an empty file with the name `io.jmix.core.Messages#clearCache` in `${jmix.core.tempDir}/triggers` directory.
By default ${jmix.core.tempDir} equals to `.jmix/temp`
