### ISSUE TITLE
Refactor platform CSS class names naming

### ISSUE THREAD

**Issue by glebfox** [Haulmont/jmix-ui#469]
Refactor css class names, scss constants and mixins prefixes:
* `cuba` > `jmix`
* `c` > `jmix`

**For QA**

1. Check that new projects looks the same
2. Check that existing projects can be successfully migrated (manually rename styles)
3. Check that screen templates contains new styles (main, login) 
4. Check that screens/components of the following add-ons still look pretty:
   1. Email templates
   2. PivotTable
   3. Reports
   4. BPM

**Comment by owlet1997** [comment]
Check-list:
#### Projects:
- [ ] creating new project
- [ ] migrating existing project
- [ ] new project with frontend module
#### Screen templates:
- [ ] main
- [ ] login
#### Add-ons:
- [ ] Email templates
- [ ] PivotTable
- [ ] Reports
- [ ] BPM
