### ISSUE TITLE
Make the caption attribute required in XSD for jpqlFilter

### ISSUE THREAD

**Issue by sukhova** [Haulmont/jmix-ui#476]
Note that in the `JpqlFilterConditionEdit` screen, the **Caption** field is required. Thus, in the xml-descriptor, the `caption` attribute must also be required.

**Comment by glebfox** [comment]
The `<jpqlFilter>` element represents the `JpqlFilter` component that has an optional caption as any other UI component. `JpqlFilterConditionEdit` is a specific use case.
