### ISSUE TITLE
PivotExcelExporter should apply styling for Double and Integer cells in exported file

### ISSUE THREAD

**Issue by Flaurite** [Haulmont/jmix-ui#479]
### Changes
Double and Integer values from PivotTable now apply Datatype formatting.

**Breaking Changes**
`PivotDataCell.Type` enum has changed values from:
```
STRING, NUMERIC, DATE_TIME, DATE, TIME
```
To
```
STRING, INTEGER, DECIMAL, DATE_TIME, DATE, TIME
```
To configure decimal format you can use the following keys:
- `decimalFormat` - used in the application to format visible values, default value: `#,##0.##`
- `pivotExcelExporter.doubleFormat` - used as cell style in the excel, default value: `#,##0.00##############`

### QA
Test with EN and RU locales

Output before fix:
`6.47225834416992`
Output after:
`6.67`

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 1.1.0-SNAPSHOT
Jmix Studio plugin version: 1.1.SNAPSHOT3442-211
IntelliJ version: IntelliJ IDEA 2021.1.3 (Community Edition)

Verified.
