### ISSUE TITLE
Describe Label, Link, Slider, ProgressBar and Calendar components using Studio meta-annotations

### ISSUE THREAD

**Issue by GlebDurygin** [Haulmont/jmix-ui#481]
Studio issue: https://youtrack.jmix.io/issue/JST-1362

### QA
Check that Label, Link, Slider(new), ProgressBar and Calendar components work the same as before

**Comment by imorenov94** [comment]
Need to support next attributes for Label component:
- enable
- responsive

**Comment by imorenov94** [comment]
Should fix value for dataContainer attribute
