### ISSUE TITLE
Large/Small size doesn't apply to filter>add condition l

### ISSUE THREAD

**Issue by maistrenkoIulia** [Haulmont/jmix-ui#482]
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT2898-211
IntelliJ version: IntelliJ IDEA 2021.1.1 (Community Edition)

TC: run app
Theme setting>set size = small
User>Filter>add search condition
ER: list of properties should have small size
AR:
![image](https://user-images.githubusercontent.com/66992566/119376162-b3279c80-bccc-11eb-9794-79952e1bf642.png)

*note*: the same for large size

**Comment by glebfox** [comment]
Due to VAADIN internal realization, the Tree component has fixed row height, which doesn't depend on theme settings, i.e. Hover, Halo and Helium have the same tree row height thus it's impossible to apply size presets for this component.
