### ISSUE TITLE
Remove messagesPack attribute from XSD

### ISSUE THREAD

**Issue by knstvk** [Haulmont/jmix-ui#483]
Keep in jmix-cuba XSD.

## Solution

* `messagesPack` attribute has been removed from screens
* `messagesPack`/`messagePack` API renamed to `messageGroup`, e.g. `MessageBundle#getMessageGroup()`
* In order to use global message group in XML, the `msg:///` prefix must be used

**For QA**

Check that screens ignore `messagesPack` attribute and their `mesageGroup` equals to their path

**Comment by imorenov94** [comment]
The issue that needed to fix https://youtrack.jmix.io/issues/JST-1440
