### ISSUE TITLE
Remove treechildren element from Tree

### ISSUE THREAD

**Issue by glebfox** [Haulmont/jmix-ui#484]
`treechildren` is used in cuba 6 screens

**For QA**

Check that with cuba module we can load both `dataContainer` (cuba 7 screens) and `datasource` (cuba 6 screens)

**Comment by maistrenkoIulia** [comment]
cannot test because of https://youtrack.haulmont.com/issue/JST-1422

**Comment by lovtsovaik** [comment]
verified
