### ISSUE TITLE
Describe ComboBox, ValuePicker, SuggestionField and ColorPicker components using Studio meta-annotations

### ISSUE THREAD

**Issue by GlebDurygin** [Haulmont/jmix-ui#488]
Studio issue: https://youtrack.jmix.io/issue/JST-1393

### QA
Check that ComboBox, EntityComboBox, ValuePicker, ValuesPicker, EntityPicker, TagPicker, SuggestionField, EntitySuggestionField and ColorPicker components work the same as before

**Comment by imorenov94** [comment]
Should fix the attributes for components mentioned below so they don't appear into a list of properties
* EntityComboBox (optionsEnum,textInputAllowed)
* TagPicker (fieldEditable, optionsEnum)
* EntitySuggestionField (buffered, fieldEditable,stylename)
