### ISSUE TITLE
Describe ListComponent using Studio meta-annotations

### ISSUE THREAD

**Issue by GlebDurygin** [Haulmont/jmix-ui#496]
Studio issue - https://youtrack.jmix.io/issue/JST-1420

### QA
Check following components:
* Table
* TreeTable
* GroupTable
* DataGrid
* TreeDataGrid
* Tree

**Comment by imorenov94** [comment]
Need to fix "columnReorderingAllowed" attribute for GroupTable component in order to it don't appear

**Comment by GlebDurygin** [comment]
The correct attribute name is `reorderingAllowed` and the attribute should appear in the ComponentInspector.
