### ISSUE TITLE
Data loading is performed twice when applying Filter first time with a new condition

### ISSUE THREAD

**Issue by knstvk** [Haulmont/jmix-ui#502]
- Create new project
- Open Users browser
- Add condition by username, enter "ad" as a value
- Set breakpoint to io.jmix.ui.model.impl.CollectionLoaderImpl#_load
- Click Refresh
- You will stop at breakpoints twice

**Comment by glebfox** [comment]
Not a bug. By default, the `autoApply` attribute is set to `true`, i.e. no need to click the Refresh button explicitly, because filter applies by field value change event (either on blur or enter press).
