### ISSUE TITLE
Describe components for MainScreen using Studio meta-annotations

### ISSUE THREAD

**Issue by GlebDurygin** [Haulmont/jmix-ui#514]
Studio issue: https://youtrack.jmix.io/issue/JST-1446

Components to check:
* UserIndicator;
* UserActionsButton;
* TimeZoneIndicator;
* LogoutButton;
* NewWindowButton;
* WorkArea;
* InitialLayout;
* SideMenu;
* AppMenu (menu);
* Drawer.

**Comment by imorenov94** [comment]
Should fix the attributes for components mentioned below

* TimeZoneIndicator (expanded)
* AppMenu (expanded)
* Drawer (expand)

**Comment by GlebDurygin** [comment]
Fixed in Studio issue
