### ISSUE TITLE
Remember last selected locale

### ISSUE THREAD

**Issue by glebfox** [Haulmont/jmix-ui#515]
Case:
1. Create a project with several locales (e.g. _en_, _ru_)
2. Start the app and login with a locale other than the default (e.g. _ru_)
3. logout 

ER: 
The last selected locale is set in the locale filed

AR:
The default locale is set in the locale filed

### Solution

Both login screen (created with the project) and login screen with branding (created from the corresponding template) have the following changes:

* `LoginScreenAuthenticationSupport` renamed to `LoginScreenSupport`
* Initial value of `localesField` is obtained from `JmixApp#getLocale()`

**Comment by owlet1997** [comment]
Case:
create new project -> open LoginScreen.java

AR:
![image](https://user-images.githubusercontent.com/45730069/121515793-a14d3580-c9fe-11eb-8180-c338b795ae81.png)

**Comment by owlet1997** [comment]
Case:
Create new login screen using screen wizard 

AR:
the same situation

**Comment by owlet1997** [comment]
Unused injecting and import in LoginScreen.java / generated login screen:
![image](https://user-images.githubusercontent.com/45730069/121518444-89c37c00-ca01-11eb-9a3f-c1d2d0d1243a.png)
![image](https://user-images.githubusercontent.com/45730069/121518542-a65fb400-ca01-11eb-8eec-2e1c62b6564b.png)
