### ISSUE TITLE
Ability to hide PropertyFilter caption

### ISSUE THREAD

**Issue by glebfox** [Haulmont/jmix-ui#516]
### Changes
Added new attribute: `captionVisible`. Default value is `true.` It shows/hides caption of `PropertyFilter` and doesn't affect the icon.

Programmatically it can be configured by:
- isCaptionVisible();
- setCaptionVisible(boolean);

### QA
Check `captionVisible` attribute. Also, try to combine with other attributes like icon or custom caption. Try to change `captionVisible` or smth else at runtime. Try your cases.

**Comment by reznikova21** [comment]
1.2.0-SNAPSHOT - verified
