### ISSUE TITLE
Upgrade org.webjars:jquery to version 3.5.0 or higher

### ISSUE THREAD

**Issue by knstvk** [Haulmont/jmix-ui#551]
See:
https://snyk.io/vuln/SNYK-JAVA-ORGWEBJARS-479774
https://snyk.io/vuln/SNYK-JAVA-ORGWEBJARS-565171

### QA
Please, do smoke test for the following components:
- PivotTable;
- File upload;
- GrapesJs components
- Charts and its export;

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 1.1.0-SNAPSHOT
Jmix Studio plugin version: 1.1.SNAPSHOT3487-212
IntelliJ version: IntelliJ IDEA 2021.2.1 (Ultimate Edition)
