### ISSUE TITLE
DataGrid does not close row details if item was removed

### ISSUE THREAD

**Issue by Flaurite** [Haulmont/jmix-ui#552]
#### Steps to reproduce
1. Download attached project: [demo.zip](https://github.com/Haulmont/jmix-ui/files/6708026/demo.zip)

2. Open: _SandBox -> Demo Order Browse_
3. Remove first item from DataGrid
4. Try to close row details in any row

**AR**
Row details still opened and content disappears
![image](https://user-images.githubusercontent.com/22093943/123237017-58ad7600-d4ee-11eb-9683-cc6acc566f01.png)

Wait for:
- https://github.com/vaadin/framework/issues/12211
- https://github.com/vaadin/framework/issues/12328

**Comment by Flaurite** [comment]
Wait for Vaadin 8.13.2

**Comment by Flaurite** [comment]
Related to https://github.com/Haulmont/jmix-ui/issues/597

**Comment by reznikova21** [comment]
1.1.0 - verified
