### ISSUE TITLE
Popup-button items order in filter add condition dialog is always different

### ISSUE THREAD

**Issue by gorbunkov** [Haulmont/jmix-ui#558]
1. Create new Jmix project and run it
2. Open the Users browse screen and click the "Add search condition" button on the generic filter component
3. Expand the "Create" pupup of the "Add condition" dialog
4. The popup items order is property - JPQL - Group:
![Screenshot 2021-06-25 at 13 38 51](https://user-images.githubusercontent.com/7888486/123405707-2289f800-d5bb-11eb-8378-98644bdc08fc.png)

5. Stop the application and start it again
6. Open the "Add condition" dialog screen again

AR: The pupup menu items order is different:
![Screenshot 2021-06-25 at 13 39 38](https://user-images.githubusercontent.com/7888486/123405791-3b92a900-d5bb-11eb-8eaa-deadb7e13ca9.png)

ER: pupup button items are always displayed in the same order

**Comment by konyashkina** [comment]
Tested on:
Ubuntu 18.04
Windows 10 Pro

Jmix version: 1.0.999-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT3236-211
IntelliJ version: IntelliJ IDEA 2021.1.3 (Community Edition)

Verified.
