### ISSUE TITLE
Refactor AppUI

### ISSUE THREAD

**Issue by gorbunkov** [Haulmont/jmix-ui#57]
* Get Rid of App class: 
In CUBA `AppUI` instance always had one-to-one `App` instance (usually `DefaultApp`). Probably there is no need to have this separate App class and all functionality can be implemented in AppUI

* Ability to override UI infrastructural beans
Currently it's quite tedious to provide custom implementation of Screens, Notifications, Dialogs and other UI beans.
Consider using @UIScope.

**Comment by web-devel** [comment]
UI infrastructural beans now are being instantiated as Spring beans with `UIScope`.

> In CUBA AppUI instance always had one-to-one App instance (usually DefaultApp). Probably there is no need to have this separate App class and all functionality can be implemented in AppUI

These beans have different scopes: `VaadinSessionScope` for `App` and `UIScope` for `AppUI` so this separation left as is.
