### ISSUE TITLE
Fix style for the emptyStateLinkMessage attribute of Table in the Helium theme

### ISSUE THREAD

**Issue by sukhova** [Haulmont/jmix-ui#570]
![изображение.png](https://images.zenhubusercontent.com/5b360034b46294032187ed9d/e59c7176-81e8-481c-8167-22bf815e80af)

**Comment by lovtsovaik** [comment]
For QA: should have helium colors

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 1.1.0-SNAPSHOT
Jmix Studio plugin version: 1.1.SNAPSHOT3238-211
IntelliJ version: IntelliJ IDEA 2021.1.3 (Community Edition)
