### ISSUE TITLE
Error message not localized for non-unique value

### ISSUE THREAD

**Issue by maistrenkoIulia** [Haulmont/jmix-ui#572]
Jmix version: 1.0.0
Jmix Studio plugin version: 1.0.0-211
IntelliJ version: IntelliJ IDEA 2021.1.3 (Community Edition)

TC: create entity>add attribute, set unique = true
create crud screens
run app>create entity, set attr value = 1>ok
create another entity, set attr value = 1>ok
ER: human-friendly message should be displayes
AR:
![image](https://user-images.githubusercontent.com/66992566/124148091-617aea80-daa0-11eb-9971-223e6e70f8b8.png)

**Comment by Flaurite** [comment]
@maistrenkoIulia hi! There is an ability to customize the error message. Try to add the following to the message pack:
```
databaseUniqueConstraintViolation.UC_PERSON_ONE=My custom unique error message
```
