### ISSUE TITLE
Message localization hasn't been displayed for @NotNull annotated attribute

### ISSUE THREAD

**Issue by maistrenkoIulia** [Haulmont/jmix-ui#573]
Jmix version: 1.0.0
Jmix Studio plugin version: 1.0.0-211
IntelliJ version: IntelliJ IDEA 2021.1.3 (Community Edition)

TC: create entity>creatу attribute
by designer set for NonNull:
- enabled = true
- create message ('please fill me')
create crud screens
run app>create entity>don't fill value in attribute>ok
ER: please fill me' notification
AR:
![image](https://user-images.githubusercontent.com/66992566/124148508-c20a2780-daa0-11eb-961c-1708feccf215.png)

*note:*  the same problem for min/max/negative validations

**Comment by Flaurite** [comment]
The problem occurs due to Studio entity designer generates message without a package. Created an issue: https://youtrack.cuba-platform.com/issue/JST-1670
