### ISSUE TITLE
Fix style for the emptyStateLinkMessage attribute of Table in the Helium theme (port to 1.0.x)

### ISSUE THREAD

**Issue by glebfox** [Haulmont/jmix-ui#583]
See: https://github.com/Haulmont/jmix-ui/issues/570

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 1.0.999-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT3236-211
IntelliJ version: IntelliJ IDEA 2021.1.3 (Community Edition)
