### ISSUE TITLE
Popup-button items order in filter add condition dialog is always different (port to 1.0)

### ISSUE THREAD

**Issue by knstvk** [Haulmont/jmix-ui#586]
See #558

**Comment by konyashkina** [comment]
Tested on:
Ubuntu 18.04
Windows 10 Pro

Jmix version: 1.0.999-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT3236-211
IntelliJ version: IntelliJ IDEA 2021.1.3 (Community Edition)

Verified.
