### ISSUE TITLE
Add options to StudioProperty annotation for the hierarchyProperty attribute of the Tree, TreeDataGrid, TreeTable components

### ISSUE THREAD

**Issue by GlebDurygin** [Haulmont/jmix-ui#591]
1) Create a screen with `Tree` or `TreeDataGrid` or `TreeTable` component
2) Try to set value for `hierarchyProperty` attribute using ComponentInspector

* Actual behavior 
Valid options - all properties of entity from `dataContainer`
```
@StudioProperty(name = "hierarchyProperty", type = PropertyType.PROPERTY_PATH_REF, typeParameter = "E",
        required = true)
```

* Expected behavior 
Valid options - all entity properties of entity from `dataContainer`
```
@StudioProperty(name = "hierarchyProperty", type = PropertyType.PROPERTY_PATH_REF, typeParameter = "E",
        required = true, options = {"to_one", "to_many"})
```

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 1.1.0-SNAPSHOT
Jmix Studio plugin version: 1.1.SNAPSHOT3437-211
IntelliJ version: IntelliJ IDEA 2021.1.3 (Community Edition)

Verified.
