### ISSUE TITLE
Attribute value isn't displayed in DataGrid

### ISSUE THREAD

**Issue by maistrenkoIulia** [Haulmont/jmix-ui#594]
Jmix version: 1.1.0-SNAPSHOT
Jmix Studio plugin version: 1.1.SNAPSHOT3217-211
IntelliJ version: IntelliJ IDEA 2021.1.3 (Community Edition)

TC:
Create entity Person with name attribute>create crud screens
For browser descriptor substitute table to Datagrid
run app
Application>Person>create>set name value>ok
ER: name value should be displayed in person browser
AR:
![image](https://user-images.githubusercontent.com/66992566/125274776-57b67a00-e31f-11eb-8704-219925db350d.png)

**Comment by glebfox** [comment]
@maistrenkoIulia could you please attach generated XML?

**Comment by maistrenkoIulia** [comment]
@glebfox issue reproduced only in case user manually has been changed groupTable to dataGrid
[user-browse.xlm.txt](https://github.com/Haulmont/jmix-ui/files/6806531/user-browse.xlm.txt)

**Comment by glebfox** [comment]
Not a bug. When manually migrating from Table to DataGrid all column `id` attributes must be replaced with `property`. @maistrenkoIulia attached XML isn't related to the issue description.
