### ISSUE TITLE
Table Deselect All action takes lots of time to perform

### ISSUE THREAD

**Issue by Flaurite** [Haulmont/jmix-ui#599]
### Description
See https://github.com/cuba-platform/cuba/issues/3212

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 1.1.0-SNAPSHOT
Jmix Studio plugin version: 1.1.SNAPSHOT3317-211
IntelliJ version: IntelliJ IDEA 2021.1.3 (Community Edition)
Chrome 92.0.4515.107, Firefox 90.0.2
