### ISSUE TITLE
Add minHeight and minWidth attributes to Table and DataGrid (port to 1.0)

### ISSUE THREAD

**Issue by Flaurite** [Haulmont/jmix-ui#601]
### Description
See https://github.com/Haulmont/jmix-ui/issues/598

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 1.0.999-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT3318-211
IntelliJ version: IntelliJ IDEA 2021.1.3 (Community Edition)
