### ISSUE TITLE
Table Deselect All action takes lots of time to perform (port to 1.0)

### ISSUE THREAD

**Issue by Flaurite** [Haulmont/jmix-ui#606]
### Description
See https://github.com/Haulmont/jmix-ui/issues/599

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 1.0.999-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT3318-211
IntelliJ version: IntelliJ IDEA 2021.1.3 (Community Edition)
Chrome 92.0.4515.107, Firefox 90.0.2
