### ISSUE TITLE
Pagination does not update the number of pages if filtering is applied

### ISSUE THREAD

**Issue by Flaurite** [Haulmont/jmix-ui#611]
### Steps to reproduce
1. Create some entity and screens
2. Add pagination component to the browse screen. Set `itemsPerPageDefaultValue="1"`.
3. Create 2 entity records. In the browser screen should be 2 pages.
4. Filter one entity

**ER**
The numbers of pages is 1
**AR**
The numbers of pages is 2

### QA
1. Check that `Pagination` updates the number of pages if `Filter` is applied
2. Check that `Pagination` updates the number of pages if `PropertyFilter` is applied
3. Try with itemsPerPageVisible = true/false
4. Try to use totalCountDelegate, make sure that it is invoked:
```
@Install(to = "pagination", subject = "totalCountDelegate")
private Integer paginationTotalCountDelegate() {
    return Math.toIntExact(dataManager.getCount(my_entity_loader.createLoadContext()));
}
```
Check your cases.

**Comment by konyashkina** [comment]
Tested on: 
Jmix version: 1.1.0-SNAPSHOT
Jmix Studio plugin version: 1.1.SNAPSHOT3437-211
IntelliJ version: IntelliJ IDEA 2021.1.3 (Community Edition)

Verified.
