### ISSUE TITLE
Remove SessionInformation from SessionRegistry on logout 

### ISSUE THREAD

**Issue by knstvk** [Haulmont/jmix-ui#619]
- Include the Audit add-on
- Open Administration -> User sessions
- Login from another browser - you will see the new session
- Logout in the other browser - the session stays in the list

**Comment by konyashkina** [comment]
Tested on: 
Jmix version: 1.1.0-SNAPSHOT
Jmix Studio plugin version: 1.1.SNAPSHOT3423-211

- [X] OS: Windows 10 Pro
IntelliJ version: IntelliJ IDEA 2021.1.3 (Community Edition)
Browsers: Google Chrome 92.0.4515.131; Firefox 91.0  

- [X] OS: MasOS Big Sur
IntelliJ version: IntelliJ IDEA 2021.2 (Ultimate Edition)
Browsers: Safari 14.1.1, Google Chrome 92.0.4515.131
