### ISSUE TITLE
The DataGrid header is hidden when users reorder the columns

### ISSUE THREAD

**Issue by sukhova** [Haulmont/jmix-ui#623]
See https://github.com/cuba-platform/helium-theme/issues/56

**Comment by konyashkina** [comment]
_Tested on_
Jmix version: 1.1.0-SNAPSHOT
Jmix Studio plugin version: 1.1.SNAPSHOT3583-212
IntelliJ version: IntelliJ IDEA 2021.2.2 (Ultimate Edition)
