### ISSUE TITLE
Update components icons in components palette

### ISSUE THREAD

**Issue by natfirst** [Haulmont/jmix-ui#627]
1. Resource and resources type
2. Slider (new_jmix_icons2 zip)
3. PresentationsFacet
4. DayNames, Day, MonthNames, Month для Calendar
5. TagField (new_jmix_icons2 zip)
5. Query for TagField and EntitySuggestionField
6. ContainerProvider and LoaderProvider for Pagination
7. Validators и Validator (new_jmix_icons2 zip)
[new_jmix_icons2.zip](https://github.com/Haulmont/jmix-ui/files/6999594/new_jmix_icons2.zip)
[new_jmix_icons.zip](https://github.com/Haulmont/jmix-ui/files/6999596/new_jmix_icons.zip)

**Comment by reznikova21** [comment]
1.1.0 - verified
