### ISSUE TITLE
EditorScreen facet with create mode edits selected item in the table instead of creating a new one

### ISSUE THREAD

**Issue by Flaurite** [Haulmont/jmix-ui#633]
#### Steps to reproduce
1. Create some entity
2. Create  browser and editor screens.
3. Create some records.
4. In the browser add editor facet that is invoked on create action:
```
<editorScreen id="createEditorScreen"
              screenId="app_EntityEditor"
              listComponent="entityTable"
              editMode="CREATE"
              onAction="entityTable.create"/>
```
5. Select one record in the table and click on create button

**ER**
Editor screen contains a new item.
**AR**
Editor screen contains selected item.

**Comment by reznikova21** [comment]
1.1.0-SNAPSHOT - verified
