### ISSUE TITLE
Implement System Information action

### ISSUE THREAD

**Issue by alexbudarov** [Haulmont/jmix-ui#64]
- create fresh project
- open User Browser
- select admin user, context menu -> System Information

Exception occurs:
```
io.jmix.ui.NoSuchScreenException: Screen 'sysInfoWindow' is not defined
	at io.jmix.ui.WindowConfig.getWindowInfo(WindowConfig.java:493)
	at io.jmix.ui.action.ShowInfoAction.showInfo(ShowInfoAction.java:78)
	at io.jmix.ui.action.ShowInfoAction.actionPerform(ShowInfoAction.java:68)
	at io.jmix.ui.component.impl.WebAbstractActionsHolderComponent.lambda$setContextMenuButtonAction$0(WebAbstractActionsHolderComponent.java:157)
	at io.jmix.ui.widget.JmixButton.fireClick(JmixButton.java:77)
	at com.vaadin.ui.Button$1.click(Button.java:57)
	at java.base/jdk.internal.reflect.NativeMethodAccessorIm
```

#### General

The old `sysInfoWindow` action from the **UI** module (as well as the corresponding dialog window) has been replaced with the new `showEntityInfo` action from the **DataTools UI** module.

In order to use the `showEntityInfo` action, it must be explicitly added to a set of `Table` (`DataGrid`, `Tree`) actions, e.g.:

```
<groupTable id="usersTable"
            width="100%"
            dataContainer="usersDc"
            multiselect="true">
    <actions>
        <action id="create" type="create"/>
        <action id="edit" type="edit"/>
        <action id="remove" type="remove"/>
        <action id="refresh" type="refresh"/>
        ...
        <action id="showEntityInfo" type="showEntityInfo"/> <----  here it is
    </actions>
...
</groupTable>
```

<img width="531" alt="Screenshot 2021-01-28 at 12 11 16" src="https://user-images.githubusercontent.com/6077149/106108671-04ca7b00-6162-11eb-9f41-03263d7fe23c.png">
<img width="643" alt="Screenshot 2021-01-28 at 12 11 25" src="https://user-images.githubusercontent.com/6077149/106108680-085e0200-6162-11eb-9180-a5331d3c36cb.png">

#### Security

The following permissions must be granted in order to have access to the **Entity Information** window:

1. Full access to the `datatools_InfoValue` entity:
<img width="622" alt="Screenshot 2021-01-28 at 12 17 00" src="https://user-images.githubusercontent.com/6077149/106109537-1a8c7000-6163-11eb-857e-2a16156b5b38.png">

2. Full access to the `datatools_InfoValue` entity attributes:
<img width="614" alt="Screenshot 2021-01-28 at 12 17 22" src="https://user-images.githubusercontent.com/6077149/106109552-1d876080-6163-11eb-8cf3-9d8db75c6374.png">

3. Access to the **Entity Information** window:
<img width="511" alt="Screenshot 2021-01-28 at 12 17 42" src="https://user-images.githubusercontent.com/6077149/106109565-1fe9ba80-6163-11eb-8d76-466815cbf3df.png">

4. Add specific permission `datatools.ui.showEntityInfo`:
<img width="502" alt="Screenshot 2021-01-28 at 12 18 16" src="https://user-images.githubusercontent.com/6077149/106109579-22e4ab00-6163-11eb-9f12-72c2881834fb.png">

**Comment by glebfox** [comment]
Corresponding commits:
* https://github.com/Haulmont/jmix-ui/commit/9945c224e6ec9c120ec1af25fc960e8242fb98e5
* https://github.com/Haulmont/jmix-cuba/commit/34b85c50ee7a0b0b0bd5e4c59e54d8a787861c9c
* https://github.com/Haulmont/jmix-datatools/commit/2355e962230d9c4d93c1f0eed7eb0b2fa43966b2
* https://github.com/Haulmont/jmix-security/commit/ac74ca856bc9e3c7ecaff40adcea9891b7137946
* https://github.com/Haulmont/jmix-translations/commit/c9b0fce35f94af7023caea177f9878a1f9fbf2fd

**Comment by natfirst** [comment]
For QA: contact with @glebfox before testing
Check-list is required

**Comment by lovtsovaik** [comment]
**Check-list**
- adding the "showEntityInfo" action to the screen is available only when the "jmix-datatools-ui-starter" starter is on
- display the context action for GroupTable, Table, Tree, TreeTable, DataGrid, TreeDataGrid
- display the context action for editor tab
- display the context action only if user has a permissions
- entity information is correct: Entity Name, Entity Class, Table, ID
- trait information is shown only if trait is on (Version, Created by/date, Last modified by/date)
- trait information is correct 
- trait information is correct if change Date type or rename the annotated attributes
- script generation and copy buttons work
- _scripts are correct for all available types of Database (not tested yet)_

**Comment by lovtsovaik** [comment]
Test project [dbh.zip](https://github.com/Haulmont/jmix-ui/files/5931357/dbh.zip)

Current problems:
1. Version is not shown (see Vers browser)

2. Even if user has no specific permissions, the menu item is available from editor tab, and the error occurs when clicking on the item. Try to log in under QA/QA
<img src="https://user-images.githubusercontent.com/73226373/107014646-53f15b00-67b5-11eb-8efc-64ca87daee90.png" height="300" />

3. If the annotated attribute is renamed, the error occurs when opening entity info, see log 
[IllegalArgumentException_rename.txt](https://github.com/Haulmont/jmix-ui/files/5931401/IllegalArgumentException_rename.txt)
See Name browser

4. If the annotated attribute has another type (Date replaced by LocalDateTime of OffsetDateTime), the error occurs when opening entity info, see log 
[IllegalArgumentException_other_type.txt](https://github.com/Haulmont/jmix-ui/files/5931411/IllegalArgumentException_other_type.txt)
See Joy browser

**Comment by glebfox** [comment]
1. Fixed
2. Fixed
3. Such attributes are not intended to be renamed. Don't alter entity code scaffolded by Studio.
4. Not sure that we can alter their type, but fixed just in case

**Comment by knstvk** [comment]
> Such attributes are not intended to be renamed. Don't alter entity code scaffolded by Studio.
In fact, they can be renamed and this is fine. We should rely on annotations, not on the attribute names.
Let's create a separate issue for this.

**Comment by glebfox** [comment]
Created an issue to implement getters for audit attributes in `EntityValues`:  https://github.com/Haulmont/jmix-core/issues/77
