### ISSUE TITLE
DataGrid does not correctly redraw row details after sorting

### ISSUE THREAD

**Issue by sukhova** [Haulmont/jmix-ui#643]
You cab see this behaviour in the [Sampler](https://demo.jmix.io/sampler/#main/7/sample?id=datagrid-generated-column)

![data-grid-sort](https://user-images.githubusercontent.com/40686909/131108076-70840bdd-0538-4557-a6ac-16802ee7735c.gif)

**Comment by Flaurite** [comment]
After updating to the new Vaadin version (8.13.3) bug is not reproduced in 1.1.0-SNAPSHOT.
