### ISSUE TITLE
Fix style for sidemenu with activated selectOnClick attribute in the main screen with collapsible menu template

### ISSUE THREAD

**Issue by sukhova** [Haulmont/jmix-ui#652]
Test case:

1) Create a main screen with collapsible side menu
2) Set `selectOnClick="true"`
3) Launch the application

**AR:**
Halo theme:
![side-menu-select-click-halo.gif](https://images.zenhubusercontent.com/5b360034b46294032187ed9d/27781a87-df99-438e-b88c-4158f7f8c111)
Helium theme
![side-menu-select-click-helium.gif](https://images.zenhubusercontent.com/5b360034b46294032187ed9d/15be453a-dd71-46aa-91fd-7ced05a58e14)
Hover theme - the same

**ER:**
![side-menu-select-click-helium-er.gif](https://images.zenhubusercontent.com/5b360034b46294032187ed9d/7f6738da-3280-433e-92ec-9dcb4ddb4b84)

----
### Changes
Added new SCSS variables:
- `$jmix-sidemenu-item-selected-background` - background of selected item in SideMenu;
- `$jmix-sidemenu-item-selected-color` - text color of selected item in SideMenu;
- `$jmix-drawer-sidemenu-item-selected-background` - background color of the selected item in SideMenu that is placed in Drawer
- `$jmix-drawer-sidemenu-item-selected-color` -  color of the selected item in SideMenu that is placed in Drawer

**Comment by knstvk** [comment]
Port to 1.0 if needed.

**Comment by reznikova21** [comment]
Jmix version: 1.1.0-SNAPSHOT - verified
