### ISSUE TITLE
Remove action is not cancellable on Role assignment screen

### ISSUE THREAD

**Issue by dtaimanov** [Haulmont/jmix-ui#665]
#### Steps:
1. Create single module application using template
2. Open Users -> Role assignments 
3. Remove some role assignment and press "Cancel" button
4. Open Role assignments screen again
 
**ER:**
* deletion of role assignment is cancelled and it is present in table

**AR:**
* Role assignment removed

At the same time creation of Role assignment can be successfully cancelled

#### Additional:
fix the same situation on user substitution screen

**Comment by gorbunkov** [comment]
Commit: https://github.com/Haulmont/jmix-security/commit/124bdad9159549fa6b674dca80c3443331a9490e

**Comment by konyashkina** [comment]
_Tested on_ 
Jmix version: 1.1.0-SNAPSHOT
Jmix Studio plugin version: 1.1.SNAPSHOT3600-212
IntelliJ version: IntelliJ IDEA 2021.2.2 (Ultimate Edition)

- [x] Role assignments screen
- [x] User substitutions screen
