### ISSUE TITLE
Editing-enable button is not hidden in the composition item editor if the master editor is in view mode

### ISSUE THREAD

**Issue by knstvk** [Haulmont/jmix-ui#670]
See https://www.cuba-platform.ru/discuss/t/dobavit-po-umolchaniyu-dialogovoe-okno-s-podtverzhdeniem-sohraneniya-izmenenij/3324/9?u=krivopustov

Perhaps we should disable "Enable editing" action for composition item if master is in the view mode.

### QA
1. Download demo project: [demo.zip](https://github.com/Haulmont/jmix-ui/files/7570353/demo.zip)
2. Open _Application -> First store entities -> Films_
3. Select record with "test" name and click on "View" button
4. In the editor select "Japan" country and click on "View" button.
    Country editor **shouldn't** show "Enable editing" button.
5. Click cancel.
6. On the Film editor click on "Enable editing".
7. Select "Japan" country again  and click on "View" button.
    Country editor **should** show "Enable editing" button.

**Comment by reznikova21** [comment]
1.2.0-SNAPSHOT - verified
