### ISSUE TITLE
TagField does not implement error style

### ISSUE THREAD

**Issue by Flaurite** [Haulmont/jmix-ui#674]
#### Steps to reproduce
1. Add tagField to a screen:
```
<tagField id="tagField" required="true"/>
```
2. Launch the app and open screen.

**ER**
![image](https://user-images.githubusercontent.com/22093943/137854814-252221e7-188b-49d9-946f-c7a9d8f67225.png)

**AR**
![image](https://user-images.githubusercontent.com/22093943/135067293-ce4bdc81-f33a-4517-be99-669e46736eb6.png)

### QA
Additional cases:
1. Make sure that error state is gone if TagField with `required="true"` has a value.
2. Check that TagField with `required="true"` has asterisk in the same line in the `Form` and `HBoxLayout` or `VBoxLayout`.
3. Check that TagField with `required="true"` is highlighted in Halo, Hover and Helium theme.
4. Your cases.

**Comment by owlet1997** [comment]
**TC 2:**
used theme: helium

**AR:**
required TagField's border is not red:
![image](https://user-images.githubusercontent.com/45730069/137890478-7a188fb5-d289-4547-a370-4878d318055b.png)
