### ISSUE TITLE
Jmix productionMode property does not affect Vaadin configuration

### ISSUE THREAD

**Issue by Flaurite** [Haulmont/jmix-ui#680]
### Description
Remove `vaadin.servlet.productionMode` and use `jmix.ui.productionMode`.

### Changes
`jmix.ui.productionMode`  is `false` by default. 

### QA
1. Create new project
2. Launch the app and try to open Vaadin debug window by the following url postfix:
```
http://localhost:8080/?debug
```
The debug window in the bottom right corner should be visible.

3. Add to the application properties:
```
jmix.ui.productionMode=true
```
4. Launch the app and try to open debug window like in the case above. There is no window should be visible.

**Comment by reznikova21** [comment]
Jmix version: 1.0.999-SNAPSHOT - verified

**Comment by reznikova21** [comment]
Jmix version: 1.1.0-SNAPSHOT - verified
