### ISSUE TITLE
Fix style for the emptyStateLinkMessage attribute of DataGrid in the Helium theme (port to 1.0.x)

### ISSUE THREAD

**Issue by glebfox** [Haulmont/jmix-ui#686]
See https://github.com/haulmont/jmix-ui/issues/628

**Comment by konyashkina** [comment]
_Tested on_ 
Jmix version: 1.0.999-SNAPSHOT
Jmix Studio plugin version: 1.0.3-212
IntelliJ version: IntelliJ IDEA 2021.2.2 (Community Edition)
