### ISSUE TITLE
[UserSubstitutionsScreen] Improve commit logic

### ISSUE THREAD

**Issue by glebfox** [Haulmont/jmix-ui#689]
Currently, the `CreateAction` doesn't commit `UserSubstitutionEntity` - newly created are commited by the **OK** button of the screen, all at once, but Edit and Remove action commit immediately. Also, cancel action doesn't check if there are new entities and cancel creation without warning.

**Comment by konyashkina** [comment]
_Tested on_ 
Jmix version: 1.1.0-SNAPSHOT
Jmix Studio plugin version: 1.1.SNAPSHOT3625-212
IntelliJ version: IntelliJ IDEA 2021.2.2 (Ultimate Edition)
