### ISSUE TITLE
[DataGrid] copy editFieldGenerator when adding a generated column

### ISSUE THREAD

**Issue by glebfox** [Haulmont/jmix-ui#694]
If a user adds both `columnGenerator` and `editFieldGenerator` via `@Install` then the result generated column won't be editable, because `editFieldGenerator` is ignored while coping properties of prev column.

### Steps to reproduce
1. Change `GroupTable` in the UserBrowse to `DataGrid`
2. Set `editorEnabled="true"`
3. For `username` column in the controller use the following code:
```
@Autowired
private UiComponents uiComponents;

@Install(to = "usersTable.username", subject = "editFieldGenerator")
private Field<?> usersTableUsernameEditFieldGenerator(DataGrid.EditorFieldGenerationContext<User> editorFieldGenerationContext) {
    ComboBox<String> comboBox = uiComponents.create(ComboBox.NAME);
    Map<String, String> map = new HashMap<>();
    map.put("value1", "value1");
    comboBox.setOptionsMap(map);
    return comboBox;
}

@Install(to = "usersTable.username", subject = "columnGenerator")
private String usersTableUsernameColumnGenerator(DataGrid.ColumnGeneratorEvent<User> columnGeneratorEvent) {
    return "Generated username: " + columnGeneratorEvent.getItem().getUsername();
}
```
4. Launch the app.
5. Try to inline-edit record.

**ER**
ComboBox should be shown for the `username` column.

**AR**
"Generated username: admin" text is shown.

**Comment by reznikova21** [comment]
1.2.0-SNAPSHOT - verified
