### ISSUE TITLE
Table does not show a popup for long text if the column is not first

### ISSUE THREAD

**Issue by Flaurite** [Haulmont/jmix-ui#705]
### Steps to reproduce
1. Download attached project: [demo-table-click.zip](https://github.com/Haulmont/jmix-ui/files/7439388/demo-table-click.zip)
2. Open _Orders_
3. Try to click on cut text:
![image](https://user-images.githubusercontent.com/22093943/139385875-b0b0f6f0-d8e1-43c1-8b93-d4e415ca135b.png)

**ER**
![image](https://user-images.githubusercontent.com/22093943/139385962-ba37ba6d-beab-4af2-bc67-5dd7179fe1cd.png)

**AR**
Nothing happens

**Comment by reznikova21** [comment]
1.2.0-SNAPSHOT - verified
