### ISSUE TITLE
Incorrect menu items alignment

### ISSUE THREAD

**Issue by aiden-izumi** [Haulmont/jmix-ui#708]
I mean that an item is a menu.item or the root of a menu

When creating a tree of items (a menu inside an another menu) they are align incorrect 

What is expected - margin of an item of level 1 will be the same as margin of the root of menu level 2
What is got - margin of the root of menu level 2 is the same as margin of the root of menu level 1
(check attached screenshot)

Side menu is used in main screen

How to reproduce:
- Create a Jmix project via Intellij Idea Jmix Studio plugin (1.1.0 is the version of Jmix Framework in my case)
- Create a menu-tree (example file is attached)
- Launch the application

[example-menu.txt](https://github.com/Haulmont/jmix-ui/files/7458236/example-menu.txt)

How it looks:
![how it looks](https://user-images.githubusercontent.com/51899225/139795137-fbea4a31-067b-4cb7-80c2-ff966fa903c1.png)

**Comment by Flaurite** [comment]
Reopened with the following bug:
![image](https://user-images.githubusercontent.com/22093943/141729756-dcf9777c-e375-4d94-942d-558adfda3153.png)

Reproduced in the collapsed menu.

**Comment by reznikova21** [comment]
1.2.0-SNAPSHOT - verified
