### ISSUE TITLE
FileUpload component doesn't show file name

### ISSUE THREAD

**Issue by gorbunkov** [Haulmont/jmix-ui#714]
Add fileUpload field to the screen:

```xml
<fileUpload id="fileUpload" showFileName="true"/>
```

Run the application and upload the file using the component.

Actual result: the `attachment (12kb)` text is written instead of file name

![image](https://user-images.githubusercontent.com/7888486/140908380-cdd14da7-092d-4a04-8fcd-eaf3b0178cdd.png)

Expected result: the uploaded file name is displayed

**Comment by glebshalyganov** [comment]
See https://github.com/Haulmont/jmix-localfs/issues/4

**Comment by reznikova21** [comment]
1.2.0-SNAPSHOT - verified
