### ISSUE TITLE
Support cross-datastore references in BulkEditWindow screen

### ISSUE THREAD

**Issue by Flaurite** [Haulmont/jmix-ui#731]
### Description
See forum: [topic](https://forum.jmix.io/t/bulkedit-doesnt-work-with-cross-datastore-reference/704)
And pull request: https://github.com/Haulmont/jmix-ui/pull/725

### QA
1. Download test project: [demo.zip](https://github.com/Haulmont/jmix-ui/files/7560336/demo.zip)
2. Open _Application -> First store entities -> GuestInfoes_ 
3. Edit some record using BulkEdit action

The field for cross-datastore reference should be shown.
Value for this field should be saved after committing changes.

**Comment by reznikova21** [comment]
1.2.0-SNAPSHOT - verified
