### ISSUE TITLE
TextField does not take into account the Length attribute of the Column annotation

### ISSUE THREAD

**Issue by Flaurite** [Haulmont/jmix-ui#733]
### Steps to reproduce
1. Create an entity
2. Add column with string datatype and setup Length = 2
3. Create browser/editor screens
4. Try to create record

**ER**
Field cuts symbols if the length is greater than 2

**AR**
![image](https://user-images.githubusercontent.com/22093943/142143664-dd9bcd44-218b-4bfe-b966-2a92d32f058c.png)

**Comment by reznikova21** [comment]
Jmix version: 1.2.0-SNAPSHOT - verified
