### ISSUE TITLE
unfetched attribute error on "metaproperty"

### ISSUE THREAD

**Issue by klaus7** [Haulmont/jmix-ui#750]
This line ...
```
                Object value = EntityValues.getValue(srcEntity, propertyName);
```
... throws an unfetched attribute error in some occasions in my project.

I fixed it by adding ...
```
&& !property.isReadOnly()
```
before this line: https://github.com/Haulmont/jmix-ui/blob/f592b0b8f4e6647a9b9a0f50080b469bf56fb199/ui/src/main/java/io/jmix/ui/model/impl/DataContextImpl.java#L274

And it works. That should be ok, because I would never want to set a read-only property anyway.

**Comment by dtaimanov** [comment]
It probably has been fixed in https://github.com/Haulmont/jmix-data/issues/102
