### ISSUE TITLE
Editor screen has unsaved changes if TagPicker is used

### ISSUE THREAD

**Issue by Flaurite** [Haulmont/jmix-ui#753]
### Description
See forum: [topic](https://forum.jmix.io/t/tagpicker-problem-test-project-included/799).

The same problem with ValuesPicker.

### Steps to reproduce

1. Download demo project: [tagpickerproblem.zip](https://github.com/Haulmont/jmix-ui/files/7639955/tagpickerproblem.zip)
2. Open _Application -> Tag holder entities_ -> select and edit record
3. Try to close editor without changes

**ER**
Editor closed

**AR**
Dialog with unsaved changes is appeared.

**Comment by lovtsovaik** [comment]
For QA: test saving with both TagPicker and ValuesPicker components

**Comment by reznikova21** [comment]
1.2.0-SNAPSHOT - verified
