### ISSUE TITLE
Export of FilterConfiguration does not work

### ISSUE THREAD

**Issue by GlebDurygin** [Haulmont/jmix-ui#762]
Forum topic:
https://forum.jmix.ru/t/ne-rabotaet-eksport-konfiguraczii-filtrov-v-inspektore-sushhnostej/247

#### EntityAttributeSerializationExtension
An extension point (class **EntityAttributeSerializationExtension**) has been added to the mechanism for serializing and deserializing an entity to JSON, which is implemented in the `EntitySerialization` bean.
The user can use this extension point to define their own logic for serializing and deserializing the entity attribute value to JSON. The desired extension is selected using the `EntityAttributeSerializationExtension#supports(MetaProperty)` method.

For the filter configuration, its own implementation of the extension was created (see `FilterConditionAttributeSerializationExtension`). The user can override this behavior by creating an extension as a bean and setting it to a higher order than the `FilterConditionAttributeSerializationExtension`.

#### EntityAttributeImportExtension
An extension point (class **EntityAttributeImportExtension**) has been added to the entity import mechanism, which is implemented in the `EntityImportExport` bean.
The user can use this extension point to define their own logic for importing the entity attribute value. The desired extension is selected using the `EntityAttributeImportExtension#supports(MetaProperty)` method.

For the filter configuration, its own implementation of the extension was created (see `FilterConditionAttributeImportExtension`). The user can override this behavior by creating an extension as a bean and setting it to a higher order than the `FilterConditionAttributeImportExtension`.

### QA
Check that user can import and export FilterConfiguration

**Comment by kendovitskii** [comment]
failed at 
Importing FilterConfiguration as JSON file
TC:
1. Create new project
2. Add Data Tools addon
3. Run application -> open app from http://localhost:8080
4. Go to -> Administration->Entity Inspector 
5. In "Entity type" choose -> Configuration (ui_FilterConfiguration)
6. Create new filter configuration preset 
7. Export created configuration as JSON and as ZIP
8. Delete configuration
9. Try import configuration from ZIP and from JSON files
ER: Configuration successfully imported from both files.
AR: Error when importing from JSON file
![json import](https://user-images.githubusercontent.com/97451999/154052940-95e3cccd-0168-4177-aeda-7ee11fa3e13f.PNG)

**Comment by kendovitskii** [comment]
Verified on 
studio version 1.2.0-RC1
