### ISSUE TITLE
Filter value cleared after operator was changed

### ISSUE THREAD

**Issue by n-13** [Haulmont/jmix-ui#776]
![image](https://user-images.githubusercontent.com/13851473/149332990-a3f8edef-1b67-4695-8dda-dc0d4f20b460.png)
![image](https://user-images.githubusercontent.com/13851473/149333026-0e0ceb2e-9bb1-4477-be4d-97ed4bfe34ac.png)

For convenience value must be preserved for similar operators "=", ">=", "<=", etc.
And must be cleared when changed from "=" to "Is set"

**Comment by GlebDurygin** [comment]
#### Solution
The value of valueComponent will only be reset if the operation type changes.
Types:
* PropertyFilter#Type#VALUE
    * PropertyFilter#Operation#EQUAL (=)
    * PropertyFilter#Operation#NOT_EQUAL (<>)
    * PropertyFilter#Operation#GREATER (>)
    * PropertyFilter#Operation#GREATER_OR_EQUAL (>=)
    * PropertyFilter#Operation#LESS (<)
    * PropertyFilter#Operation#LESS_OR_EQUAL (<=)
    * PropertyFilter#Operation#CONTAINS (contains)
    * PropertyFilter#Operation#NOT_CONTAINS (doesn't contains)
    * PropertyFilter#Operation#STARTS_WITH (starts with)
    * PropertyFilter#Operation#ENDS_WITH (ends with)
* PropertyFilter#Type#UNARY
    * PropertyFilter#Operation#IS_SET (is set)
* PropertyFilter#Type#LIST
    * PropertyFilter#Operation#IN_LIST (in)
    * PropertyFilter#Operation#NOT_IN_LIST (not in)
* PropertyFilter#Type#INTERVAL
    * PropertyFilter#Operation#DATE_INTERVAL (in interval)
    
#### QA
Check that when changing an operation with the same type, the value of the valueComponent is not reset

**Comment by Afanasevaa36** [comment]
master-b4040-verified
