### ISSUE TITLE
ExcelExport don't print a colon, if there picked "export all" action-type

### ISSUE THREAD

**Issue by GeorgiyO** [Haulmont/jmix-ui#784]
if use 'group' tag for table's column:
![image](https://user-images.githubusercontent.com/44098718/152951466-0d15b221-aba7-4007-b94a-a21bc5e1f40b.png)

Table will looks like:
![image](https://user-images.githubusercontent.com/44098718/152951614-57a16420-9edd-4c7c-bdbf-e485f2956e87.png)

Then, when use excelExport action, if pick selected-only columns, get report:
![image](https://user-images.githubusercontent.com/44098718/152952319-abec9868-235b-4775-a6e1-d9e5bb32106b.png)

But, if pick all columns, get report:
![image](https://user-images.githubusercontent.com/44098718/152952465-0e0a5004-8716-4129-a4ba-32dff6a38883.png)

So, first column (exclusively group-column), will not be printed to an excel-export

**Comment by kendovitskii** [comment]
Verified on 
1.3.999 SNAPSHOT
