### ISSUE TITLE
Exception at screen opening leads to inability to close the screen

### ISSUE THREAD

**Issue by mariodavid** [Haulmont/jmix-ui#786]
### Scenario

Given the following screens:
* ProductBrowse
* ProductEdit
When opening the ProductEdit screen from the ProductBrowse screen and during initialization of the screen an exception occurs (like unfetched attribute exception).

### Actual Behavior
After clicking away the exception that is displayed via the exception dialog and trying to close the screen via (x), another exception occurs stating: `Illegal State exception: Screen is not opened rys_Product.browse`

![1-unfetched-execption-happens-during-screen-initialization](https://user-images.githubusercontent.com/817400/152988989-0b7545fb-455c-4e9d-8d1a-caf456874524.png)

![2-when-closing-screen-it-is-not-possible-anymore](https://user-images.githubusercontent.com/817400/152989007-69deeb59-416e-47c2-88f6-f492bedd97cb.png)

It is only possible to get rid of the broken screen, by logging out and logging in again.

### Expected behavior

There are two possible options, that would be acceptable.

1. the ProductEdit screen is immediately closed and the ProductBrowse screen is displayed again
2. the ProductEdit screen is still shown, but when hitting the close (x) button, the "broken" screen is closed and the ProductBrowse screen is shown again

**Comment by glebfox** [comment]
The reasons for the exception can vary, even making the entire screen layout unresponsive to user interactions. That is why the **Unexpected error** dialog contains the _Logout_ button, which is the most reliable way to handle exceptions without reopening the app in a new browser tab.
