### ISSUE TITLE
URL state isn't preserved for the root window when opened in a new browser tab

### ISSUE THREAD

**Issue by glebfox** [Haulmont/jmix-ui#787]
Case 1:

* Run attached application: [demo.zip](https://github.com/Haulmont/jmix-multitenancy/files/8041779/demo.zip)
* Open a **NEW** browser tab and enter `http://localhost:8080/#login?tenantId=t1` in address, press Enter
* The URL is changed to `http://localhost:8080/#login`.

Case 2:

* Login to the app.
* Open a **NEW** browser tab and enter `http://localhost:8080/#main?test=1` in address, press Enter
* The URL is changed to `http://localhost:8080/#main`

**Comment by Afanasevaa36** [comment]
Jmix version: 1.2.0-SNAPSHOT - verified
