### ISSUE TITLE
Add unsupportedHandlers parameter to StudioComponent, StudioFacet and StudioElement annotations

### ISSUE THREAD

**Issue by GlebDurygin** [Haulmont/jmix-ui#788]
There is a problem that the UI component has a set of unsupported handlers that it acquired from the parent component (for example - EntityComboBox does not support `setFormatter` and `addFieldValueChangeListener` handlers). Such handlers are displayed in the Studio (ComponentInspector -> Handlers panel; Generate Handler panel; GenerateHandlerForComponentIntention) and confuse users.

Studio issue: https://youtrack.jmix.io/issue/JST-2619

### Solution
It was decided to add `unsupportedHandlers` parameter to the `@StudioComponent`, `@StudioFacet` and `@StudioElement` annotations that will define the names of unsupported handlers

### QA
Check that unsupported handlers don't appear in the following places:
1) `Component Inspector` -> `Handlers` panel
<img width="747" alt="Снимок экрана 2022-02-17 в 14 40 42" src="https://user-images.githubusercontent.com/35256248/154459274-7be1950b-302f-4ed2-9554-3360e80d774d.png">
2) Screen Controller -> `Generate Handler` notification panel
<img width="878" alt="Снимок экрана 2022-02-17 в 14 42 05" src="https://user-images.githubusercontent.com/35256248/154459508-5697500c-7e79-480c-b7fa-88ec55a08ea6.png">
3) Screen Descriptor -> click on component tag -> call `Generate component handler` intention
<img width="400" alt="Снимок экрана 2022-02-17 в 14 43 27" src="https://user-images.githubusercontent.com/35256248/154459712-f3c17106-e920-4732-aa3c-95e3e3cbe72a.png">

The list of unsupported handlers:
* EntityComboBox
    * addFieldValueChangeListener
    * setFormatter
    * setFieldIconProvider
* EntitySuggestionField
    * addFieldValueChangeListener

**Comment by Afanasevaa36** [comment]
Jmix version: 1.2.0-SNAPSHOT - verified
